### ISSUE TITLE
warning: %postun(WALinuxAgent-2.0.16-2.noarch) scriptlet failed, signal 15

### ISSUE THREAD

**Issue by jochenvw** [Azure/WALinuxAgent#178] opened 2016-04-23 06:21 UTC
I'm provisioning a CentOs box 7.x from the Azure images in the portal. On startup I wan to update yum packages + install Tomcat ( this is POC for customer ).

I'm using `CustomScriptExtension` to download and run [this](https://raw.githubusercontent.com/jochenvw/arm_sandbox/master/iaas_scripts/centos_update_tomcat.sh) script containing:

```
#!/bin/bash          
# some stuff

# Taken from: https://github.com/Azure/azure-quickstart-templates/blob/875d139c16c9c023dce519e6dd48c707e3473346/torque-cluster/azuredeploy.sh
sed -i "s/Defaults\s\{1,\}requiretty/Defaults \!requiretty/g" /etc/sudoers
sudo -u serveradmin sh -c "mkdir /home/serveradmin/.ssh/;echo Host worker\* > /home/serveradmin/.ssh/config; echo StrictHostKeyChecking no >> /home/serveradmin/.ssh/config; echo UserKnownHostsFile=/dev/null >> /home/serveradmin/.ssh/config"
if ! [ -f /home/serveradmin/.ssh/id_rsa ]; then
    sudo -u serveradmin sh -c "ssh-keygen -f /home/serveradmin/.ssh/id_rsa -t rsa -N ''"
fi

sudo yum update -y > update_log.txt
sudo yum install tomcat -y > instal_log.txt
```

However - this fails always and we found the following in the execution in the `.errout` of the script execution:

`Non-fatal POSTUN scriptlet failure in rpm package WALinuxAgent-2.0.16-2.noarch`

File location: `/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.4.1.0/download/0/stderr`

Checking the `update_log.txt` file shows the context of this error:

```
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
Resolving Dependencies
--> Running transaction check
---> Package ModemManager-glib.x86_64 0:1.1.0-6.git20130913.el7 will be updated
---> Package ModemManager-glib.x86_64 0:1.1.0-8.git20130913.el7 will be an update
...
...
...
  Updating   : 1:iwl1000-firmware-39.31.5.1-43.el7.noarch               329/639 
  Updating   : iwl5150-firmware-8.24.2.2-43.el7.noarch                  330/639 
  Updating   : iwl135-firmware-18.168.6.1-43.el7.noarch                 331/639 
  Updating   : iwl3160-firmware-22.0.7.0-43.el7.noarch                  332/639 
  Updating   : iwl7260-firmware-22.0.7.0-43.el7.noarch                  333/639 
  Cleanup    : WALinuxAgent-2.0.16-2.noarch                             334/639 
warning: %postun(WALinuxAgent-2.0.16-2.noarch) scriptlet failed, signal 15

```

The yum updates work but stop as soon as this error occurs. Can you guys point me to a solution?

**Comment by szarkos** [comment] 2016-04-23 17:14
That is strange.  I cannot replicate this issue with just running 'yum update' from the command line.  Can you tell me which specific CentOS image you're using?  Maybe it's some interaction with the extension, we'll need to test further.

As a quick fix you can try to exclude the WALinuxAgent package from the update.  The 2.0.16 agent works just fine, the update is a minor release:

   yum update -y --exclude=WALinuxAgent

FYI, aside from the 'sudo -u serveradmin' command, you don't necessarily need to run sudo to elevate privileges since the CustomScript extension already runs as root :)

Thanks!
Steve

**Comment by jochenvw** [comment] 2016-04-24 06:34
Hi @szarkos,
thanks for your response. Just to make sure - I tried it again and it seems to fail with the 7.1 version of CentOS. I'm pretty sure I've also seen it with 7.0 and 7.2:

```
"imageReference": {
    "publisher": "OpenLogic",
    "offer": "CentOS",
    "sku": "7.1",
    "version": "latest"
},
```

Full deployment script is [here](https://github.com/jochenvw/arm_sandbox/blob/master/iaas_scripts/template.json)

And indeed - I also didn't see this behavior when executing the yum update command line.

**Comment by jochenvw** [comment] 2016-04-24 06:50
I can confirm that the workaround works - the 'yum update -y --exclude=WALinuxAgent' that is. NOTE: my GitHub script now contains this fix

**Comment by ahmetalpbalkan** [comment] 2016-05-25 20:32
Should this issue be closed now?

**Comment by jochenvw** [comment] 2016-05-25 20:41
@ahmetalpbalkan who is your question directed to?

**Comment by ahmetalpbalkan** [comment] 2016-05-26 17:33
@jochenvw sorry I should have been more clear in my earlier comment. It looks like the issue is resolved for you. 

I can reproduce this issue, too. It prints the error you described and suddenly your script crashes (because `yum` crashes). A similar problem with yum happened to me in the past and I was not able to find any logs whatsoever. Here's my theory:

I don't think this issue is about the walinuxagent, it is more likely to be a `yum` issue.

Speaking from personal experience, we used to invoke `yum` in headless mode and redirect its output to a file in the past. This was giving us a strange freeze+crash with no output redirected even though we did `2>&1 1>file`. We never found any crash messages in the journal or any redirected output... When we changed our redirection behavior, the problem simply disappeared.

I realized you used `sudo` as well as `>` redirection, any of these might be causing this issue.  When I removed `>` redirection and `sudo` from your script it worked just fine for me...

If you really want to keep logs, I suggest doing a double-exec fork and running in the background. Here's a sample script for that:

```sh
#!/bin/bash
set -eu

exec > >(tee -ia /var/log/your.log)
exec 2>&1

# // rest of your script below
yum update -y
```

**Comment by ahmetalpbalkan** [comment] 2016-05-26 17:36
Closing the issue as the mitigation provided above works. Let us know if this does not work for you and we can reopen.

**Closed by ahmetalpbalkan** 2016-05-26 17:36 UTC

**Comment by jochenvw** [comment] 2016-05-27 12:39
hi @ahmetalpbalkan - thanks! No I'm not hung up on the logs - since the agent logs very nicely as well, I didn't realize that at the time.

**Comment by grandparoach** [comment] 2017-01-12 00:10
For what it's worth, I just experienced the exact same error.  I'm using the RHEL 7.2 image.  When I run the script with the "yum - y update" command manually, everything runs just fine with no errors.  But when it runs as the CustomScriptForLinux OSTCExtension from an ARM Template, it always hangs with the exact error message above.  I'm trying the "--exclude" work around mentioned above right now, but I thought someone would like to know that it is still a problem.

**Comment by ryan-blunden** [comment] 2017-02-22 02:50
I'm working with some folks at Microsoft on this issue and this is where they're at:

> Right now there is no supportable way to update the Azure agent package via customscript.  The agent will be restarted as part of the upgrade process, and since extensions are child processes to the agent process this restart will cause the extension to fail.
>  
> One option is to update the agent using a different mechanism such as via SSH after provisioning.  It’s also possible to use the OSPatching extension and schedule the OS to update at a later time (the “oneoff” option will not work in this case either).  Ubuntu users can also use cloud-init to upgrade at first boot, but unfortunately this is not an option for RHEL/CentOS yet.

So Microsoft know it's an issue and are working to resolve it.

**Comment by brendandixon** [comment] 2017-02-22 17:44
@ryan-blunden @grandparoach More recent versions of the Linux Agent (i.e., v2.1.5 and above) will self-update. Self-update *does not* alter the installed package, but *does* update the code managing extensions (basically, all post-provisioning logic) making the need to update the agent out-of-band must less.

**Comment by ryan-blunden** [comment] 2017-02-23 01:54
Good to hear!

We're now addressing this issue by upgrading to CentOS 7.3 which has a recently released version of the Linux Agent.

**Comment by deathcat05** [comment] 2019-08-16 17:26
I too, am running into this issue with CentOS. 

Properties for Image are as such: 
````
"imageReference": {
    "publisher": "OpenLogic",
    "offer": "CentOS",
     "sku": "7.6",
    "version": "latest"
}
```

The error I was receiving was that the agent identified WALinuxAgent-2.2.42 and tried to upgrade that from 2.2.38.
Some snippets from /var/log/messages
```
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.464190 INFO ExtHandler Agent WALinuxAgent-2.2.38 discovered update WALinuxAgent-2.2.42 -- exiting
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.515289 INFO Daemon Agent WALinuxAgent-2.2.38 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.527779 INFO Daemon Determined Agent WALinuxAgent-2.2.42 to be the latest agent
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.653977 INFO ExtHandler Agent WALinuxAgent-2.2.42 is running as the goal state agent
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.659179 INFO ExtHandler Wire server endpoint:168.63.129.16
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.673341 INFO ExtHandler Start env monitor service.
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.678678 INFO ExtHandler Configure routes
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.685659 INFO ExtHandler Gateway:None
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.689700 INFO ExtHandler Routes:None
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.718757 INFO ExtHandler Wire server endpoint:168.63.129.16
Aug 16 16:48:21 localhost python: 2019/08/16 16:48:21.722542 INFO ExtHandler WALinuxAgent-2.2.42 running as process 1630
```

More logs further down
```
 Stopping Azure Linux Agent...
Aug 16 16:51:25 localhost python: 2019/08/16 16:51:25.868823 INFO Daemon Agent WALinuxAgent-2.2.38 forwarding signal 15 to WALinuxAgent-2.2.42
Aug 16 16:51:26 localhost systemd: Stopped Azure Linux Agent.
Aug 16 16:51:26 localhost systemd: Started Azure Linux Agent.
Aug 16 16:51:26 localhost python: 2019/08/16 16:51:26.131466 INFO Daemon Azure Linux Agent Version:2.2.42
```

Then relevant output in stdout from /var/lib/waagent/custom-script/download/0
``` 
Cleanup    : WALinuxAgent-2.2.38-1.el7.noarch                           30/55
warning: %postun(WALinuxAgent-2.2.38-1.el7.noarch) scriptlet failed, signal 15
```

Output from stderr in /var/lib/waagent/custom-script/download/0
```
+ yum -y upgrade
Non-fatal POSTUN scriptlet failure in rpm package WALinuxAgent-2.2.38-1.el7.noarch
```

The workaround above did work, but would be nice to not have to specify to ignore waagent.

**Comment by pgombar** [comment] 2019-08-16 18:02
Hi @deathcat05, as of today the mitigation is still to exclude the agent package from the upgrade command, or to issue the upgrade command from an SSH session, not from an extension.

This is due to the design of dependencies between the agent and the extensions, like mentioned above:
> Right now there is no supportable way to update the Azure agent package via customscript.  The agent will be restarted as part of the upgrade process, and since extensions are child processes to the agent process this restart will cause the extension to fail.

**Comment by deathcat05** [comment] 2019-08-16 18:15
@pgombar Thanks for the quick response. Will skipping this upgrade of the waagent affect provisioning "under the hood" at all, besides the fact that the agent won't get updated?

**Comment by pgombar** [comment] 2019-08-16 18:47
@deathcat05 the agent has an auto-update functionality. Your snippet from /var/log/messages shows that the agent already self-discovered an update (2.2.42) being the latest available version and updated itself, so there is no need to update it from an extension.

There are two agent handlers running on any VM, extension handler and daemon. More info on that here: https://github.com/Azure/WALinuxAgent/wiki/FAQ

When issuing `yum upgrade`, it updates the daemon (provision handler). However, as I said, if your goal is just to have a running up-to-date agent (extension handler), there is no need to do it manually as there's an auto-update functionality.

**Comment by 00000o1** [comment] 2023-12-11 15:35
I just experienced this error too on Centos 8 on Azure in 2023. It seems the WA agent errors if updated while it is running the script that updates it! I am going to try the workaround `yum update -y --exclude=WALinuxAgent` Thank you for this from 2016 @jochenvw @ahmetb !
