### ISSUE TITLE
[2.1.5]waagent fails to create swapfile in RHEL-7 if fstype is ext3

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#347] opened 2016-08-04 09:20 UTC
Platform: RHEL-7.3 alpha build
Kernal version: 3.10.0-481.el7.x86_64

In WALA-2.1.5, it uses "fallocate" instead of "dd" to create swapfile. Check the manual, it seems that fallocate is not supported by ext3 filesystem after kernel-2.6.31.
man fallocate
"As of the Linux Kernel v2.6.31, the fallocate system call is supported by the btrfs, ext4, ocfs2, and xfs filesystems."

Steps to Reproduce:
1. Prepare a RHEL7.3 VM on Azure. Set the following lines in the /etc/waagent.conf:
ResourceDisk.Format=y
ResourceDisk.Filesystem=ext3
ResourceDisk.EnableSwap=y
ResourceDisk.SwapSizeMB=1024
2. Reboot the VM.
3. Check the swapfile:
ls -l /mnt/resource|grep swapfile
-rw-r--r--. 1 root root     0 Aug  4 14:17 swapfile
4. #free -m
              total        used        free      shared  buff/cache   available
Mem:           6968         180        6623           8         164        6605
Swap:             0           0           0

Logs:
/var/log/waagent:
2016/08/04 14:17:26.365987 ERROR run cmd 'fallocate -l 1073741824 '/mnt/resource/swapfile'' failed
2016/08/04 14:17:26.379904 ERROR Error Code:1
2016/08/04 14:17:26.389545 ERROR Result:fallocate: /mnt/resource/swapfile: fallocate failed: Operation not supported

2016/08/04 14:17:26.420215 ERROR run cmd 'mkswap /mnt/resource/swapfile' failed
2016/08/04 14:17:26.434877 ERROR Error Code:1
2016/08/04 14:17:26.444640 ERROR Result:mkswap: error: swap area needs to be at least 40 KiB

Usage:
 mkswap [options] device [size]

Options:
 -c, --check               check bad blocks before creating the swap area
 -f, --force               allow swap size area be larger than device
 -p, --pagesize SIZE       specify page size in bytes
 -L, --label LABEL         specify label
 -v, --swapversion NUM     specify swap-space version number
 -U, --uuid UUID           specify the uuid to use
 -V, --version             output version information and exit
 -h, --help                display this help and exit

2016/08/04 14:17:26.524109 ERROR run cmd 'swapon /mnt/resource/swapfile' failed
2016/08/04 14:17:26.536041 ERROR Error Code:255
2016/08/04 14:17:26.561057 ERROR Result:swapon: /mnt/resource/swapfile: insecure permissions 0644, 0600 suggested.
swapon: /mnt/resource/swapfile: read swap header failed: Invalid argument

2016/08/04 14:17:26.588520 ERROR Failed to enable swap (000005)/mnt/resource/swapfile

**Comment by brendandixon** [comment] 2016-08-04 16:08
@yuxisun1217 allocate is the accepted means for creating swap files (vs. dd) these days. Is there a reason you require ext3? ext4 is, unless I am misinformed, the standard on all distributions.

**Comment by yuxisun1217** [comment] 2016-08-05 03:20
Hi @brendandixon, I'm a QE in Red Hat and I just try it because it declares that it supports ext3 in waagent.conf and RHEL-7 also support ext3.
waagent.conf:
# File system on the resource disk
# Typically ext3 or ext4. FreeBSD images should use 'ufs2' here.
Maybe it's better to check the resource disk fstype and use "dd" if it is ext3? Or add some information in waagent.conf and WALinuxAgent README.md to introduce that? Thanks.

**Comment by brendandixon** [comment] 2016-08-05 15:57
@yuxisun1217 I appreciate that! We'll look into this further and, at least, update the documentation or provide more options.

**Comment by brendandixon** [comment] 2016-08-05 16:44
@yuxisun1217 I just spoke with @hglkrijger who had merged the PR with this feature. It is supposed to fall back to `dd` if `allocate` fails. We must have a bug in that path which we need to address. Thank you for calling this to our attention.

**Comment by hglkrijger** [comment] 2016-08-05 16:57
Yes, I think the issue is here: https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/daemon/resourcedisk/default.py#L203-L205 

If the return code from `fallocate` is not `127` we return it. In this case the return code is `1`, so we should continue with `dd`. I think we should change this code to:
```
if ret == 0: 
            return ret
```

**Comment by hglkrijger** [comment] 2016-08-11 00:16
@yuxisun1217 we have pushed a fix to master, would you be able to verify the issue is resolved?

**Comment by yuxisun1217** [comment] 2016-08-11 05:29
Hi @hglkrijger ,

It seems there's something wrong with the "dd" command:

/var/log/waagent.log:
2016/08/11 11:30:06.512064 VERBOSE run cmd 'umask 0077 && dd if=/dev/zero bs=67108864 count='/mnt/resource/swapfile' conv=notrunc of=16'
2016/08/11 11:30:06.634107 ERROR run cmd 'umask 0077 && dd if=/dev/zero bs=67108864 count='/mnt/resource/swapfile' conv=notrunc of=16' failed
2016/08/11 11:30:06.648483 ERROR Error Code:1
2016/08/11 11:30:06.653248 ERROR Result:dd: invalid number \u2018/mnt/resource/swapfile\u2019

**Comment by hglkrijger** [comment] 2016-08-11 21:07
@yuxisun1217, apologies for the bug. I have pushed a fix and tested myself on 7.2. If you would like to confirm that would be great. Thank you for finding this!

**Closed** 2016-08-11 21:07 UTC

**Comment by yuxisun1217** [comment] 2016-08-12 11:26
Hi @hglkrijger ,
Thank you for your update. I try the v2.1.5.2 and it works well now. :)

**Comment by hglkrijger** [comment] 2016-08-12 16:18
Thanks for testing @yuxisun1217!
