### ISSUE TITLE
Extension install failures timeout

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#1002] opened 2018-01-12 21:18 UTC
The Windows GA reports a status which allows a fast failure, however the Linux GA just reports 'Not ready' which essentially waits for a CRP timeout. We should investigate if there is a substatus we are missing to allow a fast failure.

**Comment by boumenot** [comment] 2018-02-15 01:15
I compared the two, and I do not see a difference.  I tried to replicate this behavior against 2.2.22, and I was not able to reproduce it.  The extension failed fast.  I may not be doing it right though.  Do you have the steps to reproduce this?  If not, I recommend we close this until we get those steps.

**Comment by hglkrijger** [comment] 2018-02-20 17:56
In the past I have reproduced this using custom script, and passing through empty config:
```
azure vm extension set -n CustomScriptForLinux -p Microsoft.OSTCExtensions -o 1.5 --public-config '{}'
```
In the case of the most recent report from OMS, the handler returned 127 due to invalid line endings.

**Comment by boumenot** [comment] 2018-04-19 23:51
I am not able to reproduce this issue with the version of the agent that is in master.

The extension now fails with the following message.  It took about a minute or two, not 90.

```text
Deployment failed. Correlation ID: 5ecdcfd8-6ce4-4d7c-9891-4f8f75ed1f03. VM has reported a failure when processing extension 'CustomScriptForLinux'. Error message: "Malformed status file [ExtensionError] Invalid status/status: failed"
```

**Comment by boumenot** [comment] 2018-04-20 20:54
Here's the status returned by CustomScriptForLinux.

```json
[
  {
    "status": {
      "status": "failed",
      "formattedMessage": {
        "lang": "en-US",
        "message": "Enable failed: Failed with error: commandToExecute is empty or invalid, Traceback (most recent call last):\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2/customscript.py\", line 68, in main\n    enable(hutil)\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2/customscript.py\", line 101, in enable\n    start_daemon(hutil)\n  File \"/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2/customscript.py\", line 251, in start_daemon\n    raise ValueError(error_msg)\nValueError: commandToExecute is empty or invalid\n"
      },
      "operation": "Enable",
      "code": "0",
      "name": "Microsoft.OSTCExtensions.CustomScriptForLinux"
    },
    "version": "1.0",
    "timestampUTC": "2018-04-20T20:50:22Z"
  }
]
```

**Comment by boumenot** [comment] 2018-04-20 21:40
The issue is CustomScriptForLinux is reporting a status/status of failed, and this is not recognized as a valid value. The correct value is error.  The agent needs to translate this value to an appropriate one when reporting status.

When value value is translating, the customer gets a much nicer response from Azure.

```text
Deployment failed. Correlation ID: ef31cba2-9065-4473-b9ee-ff593cb98faf. VM has reported a failure when processing extension 'CustomScriptForLinux'. Error message: "Enable failed: Failed with error: commandToExecute is empty or invalid, Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2/customscript.py", line 68, in main
    enable(hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2/customscript.py", line 101, in enable
    start_daemon(hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.2/customscript.py", line 251, in start_daemon
    raise ValueError(error_msg)
ValueError: commandToExecute is empty or invalid
".
```

**Closed** 2018-04-24 16:48 UTC
