### ISSUE TITLE
RDMA not ready when waagent reports provisioning complete

### ISSUE THREAD

**Issue by rupertnash** [Azure/WALinuxAgent#966] opened 2017-12-12 16:24 UTC
When provisioning RDMA VMs, waagent obviously has to install the relevant kernel modules & this requires a reboot. 

BUT it tells Azure that it's ready before the reboot, so if your program starts using the created VM as soon as the ARM template deployment has succeeded then about 2 minutes later you will experience weird errors!

Below is output of `cat /var/log/waagent.log` 
```
2017/12/12 15:13:18.562408 INFO Azure Linux Agent Version:2.2.12
2017/12/12 15:13:18.564598 INFO OS: centos 7.1.1503
2017/12/12 15:13:18.565925 INFO Python: 2.7.5
2017/12/12 15:13:18.567276 INFO Run daemon
2017/12/12 15:13:18.568752 INFO Activate resource disk
2017/12/12 15:13:18.581864 INFO Examining partition table
2017/12/12 15:13:18.658267 INFO GPT not detected, determining filesystem
2017/12/12 15:13:18.699059 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/12 15:13:18.702024 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/12 15:13:18.702207 INFO The partition is formatted with ntfs, updating partition type to 83
2017/12/12 15:13:18.704672 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/12 15:13:18.708663 INFO sfdisk -c  /dev/sdb 1 83 succeeded
2017/12/12 15:13:18.713877 INFO Format partition [mkfs.ext4 -F /dev/sdb1]
2017/12/12 15:13:22.129851 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/12 15:13:22.197471 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/12 15:13:22.200407 INFO Clean protocol
2017/12/12 15:13:22.201643 INFO Running default provisioning handler
2017/12/12 15:13:22.211678 INFO Copying ovf-env.xml
2017/12/12 15:13:22.256549 INFO Successfully mounted dvd
2017/12/12 15:13:22.275900 INFO Detect protocol by file
2017/12/12 15:13:22.276072 INFO Clean protocol
2017/12/12 15:13:22.276331 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/12 15:13:22.276415 INFO Test for route to 168.63.129.16
2017/12/12 15:13:22.276571 INFO Route to 168.63.129.16 exists
2017/12/12 15:13:22.276738 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:13:22.280312 INFO Fabric preferred wire protocol version:2015-04-05
2017/12/12 15:13:22.280802 INFO Wire protocol version:2012-11-30
2017/12/12 15:13:22.280942 WARNING Server preferred version:2015-04-05
2017/12/12 15:13:26.653584 INFO Starting provisioning
2017/12/12 15:13:26.654093 INFO Handle ovf-env.xml.
2017/12/12 15:13:26.654473 INFO Set hostname [base]
2017/12/12 15:13:26.726803 INFO Publish hostname [base]
2017/12/12 15:13:26.893873 INFO Examine /proc/net/route for primary interface
2017/12/12 15:13:26.894564 INFO Primary interface is [eth0]
2017/12/12 15:13:26.894754 INFO interface [lo] has flags [73], is loopback [True]
2017/12/12 15:13:26.894864 INFO Interface [lo] skipped
2017/12/12 15:13:26.894992 INFO interface [eth0] has flags [4163], is loopback [False]
2017/12/12 15:13:26.895119 INFO Interface [eth0] selected
2017/12/12 15:13:26.904137 INFO Examine /proc/net/route for primary interface
2017/12/12 15:13:26.904475 INFO Primary interface is [eth0]
2017/12/12 15:13:26.904954 INFO interface [lo] has flags [73], is loopback [True]
2017/12/12 15:13:26.905243 INFO Interface [lo] skipped
2017/12/12 15:13:26.905678 INFO interface [eth0] has flags [4163], is loopback [False]
2017/12/12 15:13:26.905990 INFO Interface [eth0] selected
2017/12/12 15:13:27.628720 INFO Create user account if not exists
2017/12/12 15:13:28.433686 INFO Configure sudoer
2017/12/12 15:13:28.435137 INFO Configure sshd
2017/12/12 15:13:28.436433 INFO Disabled SSH password-based authentication methods.
2017/12/12 15:13:28.436587 INFO Configured SSH client probing to keep connections alive.
2017/12/12 15:13:28.437261 INFO Deploy ssh public key.
2017/12/12 15:13:28.578962 INFO Event: name=WALinuxAgent, op=Provision, message=Provision succeed
2017/12/12 15:13:30.863092 INFO Provisioning complete
2017/12/12 15:13:40.982338 INFO RDMA: kvp daemon (hv_kvp_daemon) is running
2017/12/12 15:13:40.990129 INFO RDMA: kvp daemon running: True
2017/12/12 15:13:51.001279 INFO RDMA: found firmware version: 144.0
2017/12/12 15:13:51.471861 INFO RDMA: driver package present: microsoft-hyper-v-rdma-4.2.0.142-20170426.x86_64

2017/12/12 15:13:51.472672 INFO RDMA: driver package needs updating
2017/12/12 15:13:51.473418 INFO RDMA: updating RDMA packages
2017/12/12 15:13:51.473925 INFO RDMA: refreshing yum repos
2017/12/12 15:13:56.303321 INFO RDMA: repositories refreshed
2017/12/12 15:13:56.303678 INFO RDMA: Force installing package: msft-rdma-drivers
2017/12/12 15:14:11.795721 INFO RDMA: installation completed: msft-rdma-drivers
2017/12/12 15:14:11.797458 INFO RDMA: pkgs dir: /opt/microsoft/rdma/rhel71
2017/12/12 15:14:11.798072 INFO RDMA: found 7 files in package directory
2017/12/12 15:14:11.798497 INFO RDMA: deleting existing kvp driver packages
2017/12/12 15:14:11.828352 INFO RDMA: kvp package hypervkvpd does not exist, skipping
2017/12/12 15:14:11.852436 INFO RDMA: kvp package microsoft-hyper-v does not exist, skipping
2017/12/12 15:14:11.853025 INFO RDMA: Processing kernel mode driver: /opt/microsoft/rdma/rhel71/kmod-microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/12/12 15:14:11.853415 INFO RDMA: Try to uninstall existing version: kmod-microsoft-hyper-v-rdma
2017/12/12 15:15:10.094205 INFO RDMA: Successfully uninstaled kmod-microsoft-hyper-v-rdma
2017/12/12 15:15:10.096044 INFO RDMA: Installing kernel mode package from /opt/microsoft/rdma/rhel71/kmod-microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/12/12 15:15:34.778511 INFO RDMA: Processing user mode driver: /opt/microsoft/rdma/rhel71/microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/12/12 15:15:34.778796 INFO RDMA: Try to uninstall existing version: microsoft-hyper-v-rdma
2017/12/12 15:15:34.977173 INFO RDMA: Successfully uninstaled microsoft-hyper-v-rdma
2017/12/12 15:15:34.979500 INFO RDMA: Installing user mode package from /opt/microsoft/rdma/rhel71/microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64.rpm
2017/12/12 15:15:51.526873 INFO RDMA: driver packages installed
2017/12/12 15:15:51.527400 INFO RDMA: probing module 'hv_network_direct'
2017/12/12 15:15:51.531625 ERROR Command: 'modprobe --first-time hv_network_direct'
2017/12/12 15:15:51.531837 ERROR Return code: 1
2017/12/12 15:15:51.532320 ERROR Result: modprobe: ERROR: could not insert 'hv_network_direct': Module already in kernel

2017/12/12 15:15:51.532562 ERROR Could not load "hv_network_direct" kernel module. Run "modprobe --first-time hv_network_direct" as root for more details
2017/12/12 15:15:51.532772 INFO RDMA: driver module is not loaded; reboot required
2017/12/12 15:15:51.532980 INFO RDMA: Rebooting system.
2017/12/12 15:16:16.048046 INFO Azure Linux Agent Version:2.2.12
2017/12/12 15:16:16.050060 INFO OS: centos 7.1.1503
2017/12/12 15:16:16.050903 INFO Python: 2.7.5
2017/12/12 15:16:16.052363 INFO Run daemon
2017/12/12 15:16:16.053561 INFO Activate resource disk
2017/12/12 15:16:16.060110 INFO Examining partition table
2017/12/12 15:16:16.072404 INFO GPT not detected, determining filesystem
2017/12/12 15:16:16.076528 INFO sfdisk with --part-type failed [1], retrying with -c
2017/12/12 15:16:16.079581 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2017/12/12 15:16:16.080415 INFO The partition type is 83
2017/12/12 15:16:16.081127 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2017/12/12 15:16:16.151992 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2017/12/12 15:16:16.153615 INFO Clean protocol
2017/12/12 15:16:16.155774 INFO Provisioning already completed, skipping.
2017/12/12 15:16:26.200135 INFO RDMA: kvp daemon (hv_kvp_daemon) is running
2017/12/12 15:16:26.201934 INFO RDMA: kvp daemon running: True
2017/12/12 15:16:36.213379 INFO RDMA: found firmware version: 144.0
2017/12/12 15:16:36.288562 INFO RDMA: driver package present: microsoft-hyper-v-rdma-4.2.2.144-20170706.x86_64

2017/12/12 15:16:36.292103 INFO RDMA: driver package is up-to-date
2017/12/12 15:16:36.294013 INFO RDMA capabilities are enabled in configuration
2017/12/12 15:16:36.296278 INFO Detect protocol endpoints
2017/12/12 15:16:36.297971 INFO Clean protocol
2017/12/12 15:16:36.299356 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/12/12 15:16:36.301654 INFO Test for route to 168.63.129.16
2017/12/12 15:16:36.303551 INFO Route to 168.63.129.16 exists
2017/12/12 15:16:36.305285 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:36.313829 INFO Fabric preferred wire protocol version:2015-04-05
2017/12/12 15:16:36.315036 INFO Wire protocol version:2012-11-30
2017/12/12 15:16:36.315178 WARNING Server preferred version:2015-04-05
2017/12/12 15:16:43.677922 INFO Found RDMA details. IPv4=172.16.1.2 MAC=00:15:5D:33:FF:0B
2017/12/12 15:16:43.687699 INFO RDMA: starting device processing in the background.
2017/12/12 15:16:43.690097 INFO RDMA: device is set up
2017/12/12 15:16:43.689954 INFO Updating DAPL configuration file
2017/12/12 15:16:43.692889 INFO Installed Agent WALinuxAgent-2.2.12 is the most current agent
2017/12/12 15:16:43.693034 INFO RDMA: trying /etc/dat.conf
2017/12/12 15:16:43.694706 INFO RDMA: DAPL config not found at /etc/dat.conf
2017/12/12 15:16:43.706913 INFO RDMA: trying /etc/rdma/dat.conf
2017/12/12 15:16:43.709275 INFO RDMA: DAPL config is at: /etc/rdma/dat.conf
2017/12/12 15:16:43.712540 INFO RDMA: DAPL configuration is updated
2017/12/12 15:16:43.778382 INFO Skip setting /dev/hvnd_rdma on 4.1 or later
2017/12/12 15:16:43.779474 INFO RDMA: will update the network interface with IPv4/MAC
2017/12/12 15:16:43.783025 INFO Agent WALinuxAgent-2.2.12 is running as the goal state agent
2017/12/12 15:16:43.786016 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:43.789918 INFO Start env monitor service.
2017/12/12 15:16:43.789320 INFO Event: name=WALinuxAgent-2.2.12, op=HeartBeat, message=
2017/12/12 15:16:43.791284 INFO Configure routes
2017/12/12 15:16:43.791764 INFO Gateway:None
2017/12/12 15:16:43.792078 INFO Routes:None
2017/12/12 15:16:43.847086 INFO RDMA: network interface found: eth1
2017/12/12 15:16:43.847967 INFO RDMA: bringing network interface up
2017/12/12 15:16:43.851483 INFO RDMA: configuring IPv4 addr and netmask on interface
2017/12/12 15:16:43.858379 INFO WALinuxAgent-2.2.12 running as process 1389
2017/12/12 15:16:43.858712 INFO Set block dev timeout: sda with timeout: 300
2017/12/12 15:16:43.873411 INFO RDMA: network address and netmask configured on interface
2017/12/12 15:16:43.873641 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:43.874094 INFO Set block dev timeout: sdb with timeout: 300
2017/12/12 15:16:43.937417 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.17 downloaded successfully
2017/12/12 15:16:43.983837 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.18 downloaded successfully
2017/12/12 15:16:43.985330 INFO Agent WALinuxAgent-2.2.12 discovered WALinuxAgent-2.2.18 as an update and will exit
2017/12/12 15:16:44.708474 INFO Agent WALinuxAgent-2.2.12 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/12/12 15:16:44.713999 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.12 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/12/12 15:16:44.721535 INFO Determined Agent WALinuxAgent-2.2.18 to be the latest agent
2017/12/12 15:16:44.807282 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2017/12/12 15:16:44.809914 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:44.812897 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2017/12/12 15:16:44.813340 INFO Start env monitor service.
2017/12/12 15:16:44.814495 INFO Configure routes
2017/12/12 15:16:44.815373 INFO Gateway:None
2017/12/12 15:16:44.816700 INFO Routes:None
2017/12/12 15:16:44.832567 INFO WALinuxAgent-2.2.18 running as process 1403
2017/12/12 15:16:44.832422 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:44.837309 INFO Event: name=WALinuxAgent, op=AutoUpdate, message=, duration=0
2017/12/12 15:16:44.839978 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:45.111241 INFO Wire server endpoint:168.63.129.16
2017/12/12 15:16:45.221147 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=109
```

**Comment by hglkrijger** [comment] 2017-12-14 20:01
@szarkos it seems infeasible to ask the agent to orchestrate the provisioning signal over reboots. Do you have any thoughts on how we can improve the experience here?

**Comment by rupertnash** [comment] 2017-12-15 09:38
Surely the provision handler should just call something `rdma_handler.install_driver()` before it sends the provisioning complete event to the server? It is incorrect to report that the node is ready when the agent is about to reboot it.

**Comment by szarkos** [comment] 2017-12-18 18:53
For IB-enabled systems perhaps the RDMA code should be responsible for sending the ready signal.  It runs at every boot, so it can just send "ready" at boot time after the IP address for the IB interface is configured as long as a reboot is not pending.

The trouble is that some customers will use the HPC images with VM sizes without an IB interface (because the image contains other tools they need), and will expect provisioning to succeed even if an IB interface isn't configured.

@hglkrijger, it seems like if we fix https://github.com/Azure/WALinuxAgent/issues/841 and set "OS.EnableRDMA=auto," then we can do both.  If an RDMA interface is detected then the RDMA code will be responsible for sending the health report to the wire server, and otherwise the PA should do it.

Thoughts?

**Comment by hglkrijger** [comment] 2017-12-20 20:39
@szarkos #841 is fine, we will go build that, but having two places in the code which send the provision complete signal seems problematic. I also feel we should not hand off that responsibility when failure will lead to customer incidents. 

To me the issue is having the rdma driver doing a reboot, ideally that should go away. If that is not possible, customers have to find another way to monitor for "ready". As our direction is to remove the provision ready signal eventually, this seems inevitable anyway. 

Since we will not make these changes to the agent, I am closing this issue.

**Closed by hglkrijger** 2017-12-20 20:39 UTC
