### ISSUE TITLE
[BUG][2.2.54.2] waagent-network-setup.service failed

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2223] opened 2021-04-13 09:39 UTC
**Describe the bug: A clear and concise description of what the bug is.**
waagent-network-setup.service failed because "can't open file '/var/lib/waagent/WALinuxAgent-2.2.54.2/bin/WALinuxAgent-2.2.54.2-py2.7.egg': [Errno 2] No such file or directory"
```
2021-04-13T08:58:20.898332Z INFO ExtHandler ExtHandler Distro: redhat-8.5; OSUtil: RedhatOSUtil; AgentService: waagent; Python: 3.6.8; systemd: True; LISDrivers: Absent; logrotate: logrotate 3.14.0;
2021-04-13T08:58:20.903325Z INFO ExtHandler ExtHandler WALinuxAgent-2.2.54.2 running as process 5342
2021-04-13T08:58:20.906831Z INFO ExtHandler ExtHandler Cgroup monitoring is not supported on ['redhat', '8.5', 'Ootpa', 'Red Hat Enterprise Linux']
2021-04-13T08:58:20.907598Z INFO ExtHandler ExtHandler Starting setup for Persistent firewall rules
2021-04-13T08:58:21.782166Z INFO ExtHandler ExtHandler Firewalld service not running/unavailable, trying to set up waagent-network-setup.service
2021-04-13T08:58:21.793557Z INFO ExtHandler ExtHandler Service: waagent-network-setup.service already enabled. No change needed.
2021-04-13T08:58:21.811422Z INFO ExtHandler ExtHandler Logs from the waagent-network-setup.service since system boot:
 -- Logs begin at Tue 2021-04-13 16:56:51 CST, end at Tue 2021-04-13 16:58:21 CST. --
Apr 13 16:57:11 localhost.localdomain python3.6[555]: /usr/bin/python3.6: can't open file '/var/lib/waagent/WALinuxAgent-2.2.54.2/bin/WALinuxAgent-2.2.54.2-py2.7.egg': [Errno 2] No such file or directory
Apr 13 16:57:11 localhost.localdomain systemd[1]: waagent-network-setup.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 13 16:57:11 localhost.localdomain systemd[1]: waagent-network-setup.service: Failed with result 'exit-code'.
Apr 13 16:57:11 localhost.localdomain systemd[1]: Failed to start Setup network rules for WALinuxAgent.
```

Note: Please add some context which would help us understand the problem better
1. Start a RHEL-8 VM with WALinuxAgent installed. firewalld service is disabled.
2. Waiting for WALinuxAgent-2.2.54.2 downloaded and started.
3. Check the waagent-network-setup.service
```
# systemctl status waagent-network-setup
Warning: The unit file, source configuration file or drop-ins of waagent-network-setup.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● waagent-network-setup.service - Setup network rules for WALinuxAgent
   Loaded: loaded (/usr/lib/systemd/system/waagent-network-setup.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/waagent-network-setup.service.d
           └─10-environment.conf
   Active: failed (Result: exit-code) since Tue 2021-04-13 16:57:11 CST; 31min ago
 Main PID: 555 (code=exited, status=2)

Apr 13 16:57:11 localhost.localdomain python3.6[555]: /usr/bin/python3.6: can't open file '/var/lib/waagent/WALinuxAgent-2.2.54.2/bin/WALinuxAgent-2.2.54.2-py2.7.egg': [Errno 2] No such file or directory
Apr 13 16:57:11 localhost.localdomain systemd[1]: waagent-network-setup.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 13 16:57:11 localhost.localdomain systemd[1]: waagent-network-setup.service: Failed with result 'exit-code'.
Apr 13 16:57:11 localhost.localdomain systemd[1]: Failed to start Setup network rules for WALinuxAgent.
```

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-8.5
 - WALinuxAgent version 
WALinuxAgent-2.2.49.2 running on redhat 8.5
Python: 3.6.8
Goal state agent: 2.2.54.2

**Comment by larohra** [comment] 2021-04-14 18:31
Hey @yuxisun1217, thanks for reporting this. This error is mostly thrown when a VM is created off another VM image without properly deprovisioning it (and subsequently the agent). Can you confirm if - 
- This is a custom image
- If the base image was deprovisioned properly? To deprovision a Linux VM you need to call this command - `sudo waagent -deprovision+user`

**Comment by yuxisun1217** [comment] 2021-04-15 03:34
Hi @larohra ,

Yes it's a custom image. And it was deprovisioned by running "waagent -deprovision+user" by root account. But the installed WALA package version is WALinuxAgent-2.2.49.2 which doesn't clear the agent_network_service_path. 

Now I understand that perhaps the root cause is that the .egg file was removed during deprovisioning but waagent-network-setup.service is still enabled. IMO we can try to resolve it by:
1. Release v2.2.54.2 package from Red Hat side so that it will remove agent_network_service_path during deprovisioning.
2. Delay the agent_network_service by waiting for .egg file exists in the agent_network_service_path. (it still doesn't work in some corner case such as customer disables the autoupdate. But at least it can prevent the service failure in normal operations.)

Could you please help to evaluate that? Thanks!

**Comment by larohra** [comment] 2021-04-15 17:47
Hey @yuxisun1217, thanks for the deep dive into this and suggesting solutions for it. You are absolutely correct, the deprovision code removes the latest `.egg` file but this version of the deprovision does not clear the `agent_network_service_path` which causes this issue.

>Release v2.2.54.2 package from Red Hat side so that it will remove agent_network_service_path during deprovisioning.

I really like this option, as this would also make sure that the latest daemon version is installed in the VM too. Though would it be possible to wait for a while before doing that, maybe 1-3 weeks? The reason for the wait is because since we have just released this version, waiting would give us confidence in the new version and we can ensure no new regressions were introduced in it.
 
>Delay the agent_network_service by waiting for .egg file exists in the agent_network_service_path. (it still doesn't work in some corner case such as customer disables the autoupdate. But at least it can prevent the service failure in normal operations.)

This option is not that desirable because the whole use case of this `waagent-network-setup.service` file is to ensure that we setup firewall rules on the VM before it comes online. If we add a delay here, it would just defeat that purpose.

I would also like to take this opportunity to understand the process on how Redhat decides to update the guest agent on its VMs. Would it be possible for us to get on a call and just walk through the process? This would be really helpful for us to understand the update cadence of the agent on Redhat VMs and how we can expedite it and possibly automate this process for future releases.

Thanks a lot!

**Comment by larohra** [comment] 2021-04-20 21:17
Fixed by #2225

**Closed by larohra** 2021-04-20 21:17 UTC
Labels: by design, triaged

**Comment by yuxisun1217** [comment] 2021-07-23 09:53
Hi @lagalbra ,

So sorry I didn't see your question for a long time. We don't have a regular schedule to rebase the WALA package. Usually we only rebase the package when MSFT open a request BZ for us. And sometimes when we didn't rebase for a long time, we'll discuss with MSFT if we should rebase it.

**Comment by lagalbra** [comment] 2021-07-23 16:38
@larohra FYI on the above, as I believe @yuxisun1217 meant to tag you and not me :)

**Comment by yuxisun1217** [comment] 2021-07-26 06:36
Oops! Sorry @lagalbra ! Yes I meant @larohra :D

**Comment by larohra** [comment] 2021-07-26 15:42
@yuxisun1217 thanks for the reply! 

>Usually we only rebase the package when MSFT open a request BZ for us.

Do you know the process for this by any chance? We can proactively start reaching out to you whenever we have a new stable version is available for the repos. 

Thanks!
