### ISSUE TITLE
Check Point virtual appliance console spam from agent

### ISSUE THREAD

**Issue by jabbera** [Azure/WALinuxAgent#1146] opened 2018-05-02 15:37 UTC
Hi,

Sorry if this is a dupe, but I've searched the issue list with no luck. We deploy checkpoint R77 appliances from the marketplace via a custom ARM template. When trying to use the new serial console feature the console is spammed every three seconds with the following message:

```
2018/05/02 11:35:17.490477 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2018/05/02 11:35:20.523944 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2018/05/02 11:35:23.550757 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2018/05/02 11:35:27.584083 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
```

Can these be made silent? 

Thanks!
Mike

**Comment by boumenot** [comment] 2018-05-02 21:28
We don't support the Check Point virtual appliance, so your best bet is to work with them.  Sorry, I do not have contact information.

There is no configuration knob that ships with the stock version of the agent to suppress these message. There was a change in 2.2.20 to suppress these messages and others, but it looks like Check Point has not picked up that version of the agent.  I don't know what version that ship.

The original issue is #985.  I am closing this as dupe of that one.

**Closed by boumenot** 2018-05-02 21:28 UTC
