### ISSUE TITLE
Modifies iptables

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#267] opened 2016-06-27 06:24 UTC
waagent modifies iptables rules. This is problematic, as packet filter rules are a shared resource and will be overwritten by the admin. If access to the metadata endpoint is problematic, fix it there.

**Comment by brendandixon** [comment] 2016-06-27 18:44
@waldiTM The Azure Linux agent is responsible for multiple things, including provisioning the VM so it works correctly within Azure. In some distributions, provisioning happens outside the agent, in others the agent manages it. Part of provisioning entails manipulating the iptable rules. Certain settings are required for correct function within Azure, and in other cloud providers (depending on the features used).

Thank you for reviewing our code.

**Comment by ahmetalpbalkan** [comment] 2016-07-11 18:21
@waldiTM Closing as this is by design. If this behavior affects you in any way, please reopen an issue and we can discuss how to mitigate or a find a workaround for you.

**Closed by ahmetalpbalkan** 2016-07-11 18:21 UTC
Labels: question
