### ISSUE TITLE
Unable to load config info from /FIPS/1.0.2l-plus/Linux_x86_64/ssl/openssl.cnf

### ISSUE THREAD

**Issue by dirk385** [Azure/WALinuxAgent#1402] opened 2018-11-22 13:56 UTC
Hi,

New server SLES 12 SP3.
During install of waagent errors:
The agent won't install.
The server does not run FIPFS mode.

2018/11/22 14:54:36.942897 INFO WireServer endpoint is not found. Rerun dhcp handler
2018/11/22 14:54:36.978397 INFO Test for route to 168.63.129.16
2018/11/22 14:54:37.008584 INFO Route to 168.63.129.16 exists
2018/11/22 14:54:37.031832 INFO Wire server endpoint:168.63.129.16
2018/11/22 14:54:37.061631 INFO Fabric preferred wire protocol version:2015-04-05
2018/11/22 14:54:37.089874 INFO Wire protocol version:2012-11-30
2018/11/22 14:54:37.110951 WARNING Server preferred version:2015-04-05
2018/11/22 14:54:37.148154 ERROR Command: '/usr/bin/openssl req -x509 -nodes -subj /CN=LinuxTransport -days 730 -newkey rsa:2048 -keyout /var/lib/waagent/TransportPrivate.pem -out /var/lib/waagent/TransportCert.pem'
2018/11/22 14:54:37.225280 ERROR Return code: 1
2018/11/22 14:54:37.245136 ERROR Result: WARNING: can't open config file: /FIPS/1.0.2l-plus/Linux_x86_64/ssl/openssl.cnf
Unable to load config info from /FIPS/1.0.2l-plus/Linux_x86_64/ssl/openssl.cnf

2018/11/22 14:54:42.340405 INFO WireServer is not responding. Reset endpoint
2018/11/22 14:54:42.371974 INFO Protocol endpoint not found: WireProtocol, [000008] /var/lib/waagent/TransportCert.pem is missing.
2018/11/22 14:54:42.414232 INFO Protocol endpoint not found: MetadataProtocol, [000008] 404 - GET: http://169.254.169.254/Microsoft.Compute/identity?api-version=2015-05-01-preview
2018/11/22 14:54:42.474098 INFO Retry detect protocols: retry=77

**Comment by narrieta** [comment] 2018-12-07 23:33
@dirk385 - Are trying to install the agent on a custom image, or using an standard image from the marketlplace? Thanks

**Comment by dirk385** [comment] 2018-12-10 20:07
@narrieta 
An standard image from the marketlplace.
Before the install NetIQ Access Manager. the Agent is working fine.

After I installed NetIQ Access Manager the issue was created.
So the issue is caused due the install off NetIQ Access Manager.

I still don't understand why.

I finally get it working by doing this:
mkdir -p /FIPS/1.0.2l-plus/Linux_x86_64/ssl
ln -s /var/lib/ca-certificates/ca-bundle.pem /FIPS/1.0.2l-plus/Linux_x86_64/ssl/ca-bundle.pem
ln -s /var/lib/ca-certificates/pem /FIPS/1.0.2l-plus/Linux_x86_64/ssl/certs

**Comment by pgombar** [comment] 2019-10-24 21:59
Closing since the issue is resolved.

**Closed by pgombar** 2019-10-24 21:59 UTC
Labels: needs more information
