### ISSUE TITLE
TypeError: add_event() got an unexpected keyword argument 'msg'

### ISSUE THREAD

**Issue by enihcam** [Azure/WALinuxAgent#1021] opened 2018-01-26 04:35 UTC
```
Jan 26 01:14:39 python[220]: 2018/01/26 01:14:39.832006 INFO Event: name=WALinuxAgent, op=HeartBeat, message=1;5;484DEDE4-FD6C-4419-B815-D1412CC4B708;0, duration=0
Jan 26 01:14:39 python[220]: Exception in thread Thread-1:
Jan 26 01:14:39 python[220]: Traceback (most recent call last):
Jan 26 01:14:39 python[220]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Jan 26 01:14:39 python[220]:     self.run()
Jan 26 01:14:39 python[220]:   File "/usr/lib/python3.6/threading.py", line 864, in run
Jan 26 01:14:39 python[220]:     self._target(*self._args, **self._kwargs)
Jan 26 01:14:39 python[220]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/ga/monitor.py", line 225, in daemon
Jan 26 01:14:39 python[220]:     msg=msg)
Jan 26 01:14:39 python[220]: TypeError: add_event() got an unexpected keyword argument 'msg'
Jan 26 01:44:31 python[220]: 2018/01/26 01:44:31.968736 INFO Running Agent 2.2.20 was not found in the agent manifest - adding to list

```

**Comment by hglkrijger** [comment] 2018-01-26 06:42
Dupe of https://github.com/Azure/WALinuxAgent/issues/974

**Closed by hglkrijger** 2018-01-26 06:42 UTC
