### ISSUE TITLE
ERROR:Unable to fetch Bundle URI from manifest for Microsoft.OSTCExtensions.LinuxDiagnostic v 2.3.4

### ISSUE THREAD

**Issue by Gemakk** [Azure/WALinuxAgent#163] opened 2016-03-16 18:18 UTC
My VM extensions get into a bad state where I have to restart the waagent process myself.

Here's the logs for the specific error in waagent.log prior to shutdown:

```
2016/03/16 18:02:47 [LinuxAzureDiagnostic-0.0]Enabling ASM extension
2016/03/16 18:02:47 [LinuxAzureDiagnostic-0.0]cwd is /var/lib/waagent/Microsoft.Azure.Extensions.LinuxAsm-1.6.0
2016/03/16 18:02:47 [Microsoft.Azure.Extensions.LinuxAsm-1.0]Change log file to /var/log/azure/Microsoft.Azure.Extensions.LinuxAsm/1.6.0/extension.log
2016/03/16 18:02:52 enableCommand completed.
2016/03/16 18:02:52 SetHandlerState: Microsoft.Azure.Extensions.LinuxAsm-1.6.0, Enabled
2016/03/16 18:02:52 Enable completed for Microsoft.Azure.Extensions.LinuxAsm-1.6.0
2016/03/16 18:02:52 Processing completed for Microsoft.Azure.Extensions.LinuxAsm-1.6.0
2016/03/16 18:02:52 Found Plugin: Microsoft.OSTCExtensions.LinuxDiagnostic version: 2.3.4
2016/03/16 18:02:52 Downloading plugin manifest: Microsoft.OSTCExtensions.LinuxDiagnostic from http://rdfepirv2dm1prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions_LinuxDiagnostic_uscentral_manifest.xml
2016/03/16 18:02:52 Plugin server is: rdfepirv2dm1prdstr01.blob.core.windows.net
2016/03/16 18:02:52 ERROR:Unable to fetch Bundle URI from manifest for Microsoft.OSTCExtensions.LinuxDiagnostic v 2.3.4
2016/03/16 18:02:52 Finished processing ExtensionsConfig.xml
2016/03/16 18:02:52 ERROR:Traceback (most recent call last):
2016/03/16 18:02:52 ERROR:  File "/usr/sbin/waagent", line 5938, in main
2016/03/16 18:02:52 ERROR:    WaAgent.Run()
2016/03/16 18:02:52 ERROR:  File "/usr/sbin/waagent", line 5540, in Run
2016/03/16 18:02:52 ERROR:    goalState.ExtensionsConfig.ReportHandlerStatus()
2016/03/16 18:02:52 ERROR:  File "/usr/sbin/waagent", line 3806, in ReportHandlerStatus
2016/03/16 18:02:52 ERROR:    reportHeartbeat = json.loads(p.getAttribute("manifestdata"))[0]['handlerManifest']['reportHeartbeat']
2016/03/16 18:02:52 ERROR:  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
2016/03/16 18:02:52 ERROR:    return _default_decoder.decode(s)
2016/03/16 18:02:52 ERROR:  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
2016/03/16 18:02:52 ERROR:    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2016/03/16 18:02:52 ERROR:  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
2016/03/16 18:02:52 ERROR:    raise ValueError("No JSON object could be decoded")
2016/03/16 18:02:52 ERROR:ValueError: No JSON object could be decoded
2016/03/16 18:02:52 ERROR:
2016/03/16 18:02:52 ERROR:Exception: No JSON object could be decoded
```

**Comment by ahmetalpbalkan** [comment] 2016-05-26 17:57
@Gemakk sorry you had this experience. Did you add `LinuxAsm` extension to the VM yourself. It looks like it was expecting a configuration JSON file and it is likely (from the error) that the file is missing/empty.

Do you mind sending us the `/var/lib/waagent/ExtensionsConfig.N.xml` file (N: highest number that exists in that directory)?

**Comment by hglkrijger** [comment] 2016-06-09 17:45
This appears to be handled better in the 2.1 code; since we are moving over to that shortly, I am closing this issue. @Gemakk feel free to re-open if you see this in the >=2.1.3 agent. You can find it here: https://github.com/Azure/WALinuxAgent/releases/tag/v2.1.3 and information on how to upgrade here: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-update-agent/

**Closed by hglkrijger** 2016-06-09 17:45 UTC
Labels: needs more information

**Comment by paulmey** [comment] 2016-08-12 16:22
@ahmetalpbalkan, @hglkrijger this is actually the same as #355. The call that fails (`json.loads(p.getAttribute("manifestdata"))`) is trying to read the handlerManifest.json from the bundle (which couldn't be downloaded), but it instead encounters the extension manifest xml (with all of the bundle uri's per version) in this attribute of `p`.

**Comment by brendandixon** [comment] 2016-08-12 16:48
@paulmey @hglkrijger So the root cause, then, is mishandling of the failed download? v2.1.5+ will fix this by virtue of downloading and interpreting the Xml in an entirely different manner.

**Comment by paulmey** [comment] 2016-08-12 17:47
@brendandixon @hglkrijger indeed. This code is completely changed in 2.1.
