### ISSUE TITLE
Linux VM Agent disables existing user account when VM is created based on specialized disk

### ISSUE THREAD

**Issue by morgansimonsen** [Azure/WALinuxAgent#454] opened 2016-09-29 11:12 UTC
The Linux VM Agent seems to disable the original admin account specified during initial provisioning, if a specialized disk is used to create a new VM. If I delete a VM, but keep its disk, and then provision a new VM based on that disk, using the "createOption": "Attach" in my template or PowerShell command; the existing local admin account is disabled by placing an exclamation mark (!) in front of that user's password in /etc/shadow. This results in "Permission denied, please try again." messages when trying to log on to the new VM. Trying the exact same procedure for a Windows VM does not produce this behavior, i.e. the local user account(s) that were created during initial provisioning are still enabled. All documentation I can find says that when working with a specialized disk no additions or changes to existing user accounts should be provided or expected.

**Comment by hglkrijger** [comment] 2017-01-09 20:23
@morgansimonsen it is expected that the initial admin account (`root`) created for provisioning is disabled, but not the user account. Also, if an ssh key is provided this is not removed. If this is not the behavior you are seeing please provide the following info:
- OS and version
- agent version
- /var/log/waagent.log (after initial provisioning)
- any scripts or commands you used which can reproduce the issue

**Comment by brendandixon** [comment] 2017-04-27 20:35
@morgansimonsen Closing since we've not heard from you. Please reopen with sufficient detail to reproduce if you continue to believe an issue exists. Thank you.

**Closed by brendandixon** 2017-04-27 20:35 UTC
Labels: needs more information
