### ISSUE TITLE
WALinuxAgent and managed disks - VM not provisioned

### ISSUE THREAD

**Issue by ecgg** [Azure/WALinuxAgent#676] opened 2017-04-19 09:43 UTC
Hi.

WALinuxAgent and managed disks seem to have teething issues.

I prepared a custom RHEL 7.3 images as described on [Prepare a Red Hat-based virtual machine for Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/redhat-create-upload-vhd). The WALinuxAgent installed is version 2.2.4

After uploading the VHD to azure, I created a VM of it using the VHD as source for a managed disk. This all worked however the provisioning failed (user not created, host name not set). Checking `waagent.log` I noticed

    2017/04/19 11:37:48.937336 ERROR [ProtocolError] Provisioning failed: (000008)(000007)Failed to get dvd device
    2017/04/19 11:37:53.856294 ERROR Event: name=WALA, op=Provision, message=Failed to copy ovf-env.xml: (000008)(000007)Failed to get dvd device

Since this seems more a provisioning issue than a WALinuxAgent issue, I already created Microsoft support ticket 117032015477578 for this. I just wonder if you were already aware of the general issue.

Included the waagent.log, waagent.conf and boot.log of an impacted instance.

[boot.log.txt](https://github.com/Azure/WALinuxAgent/files/933110/boot.log.txt)
[waagent.conf.txt](https://github.com/Azure/WALinuxAgent/files/933108/waagent.conf.txt)
[waagent.log.txt](https://github.com/Azure/WALinuxAgent/files/933109/waagent.log.txt)

Regards,
Gregory

**Comment by yuxisun1217** [comment] 2017-04-19 10:51
hi @ecgg ,

I'm trying to reproduce it. Could you please provide the region and vm size? And is it a 100% reproducible issue? Thank you very much!

Best regards,
Yuxin Sun

**Comment by ecgg** [comment] 2017-04-19 10:55
Hi @yuxisun1217 

Region is westeurope, VM size is Standard_DS1. So far I've been able to reproduce it all the time

Thanks
Gregory

**Comment by ecgg** [comment] 2017-04-19 12:38
Forgot to include this; after the VM is up, there is no cdrom device

    [root@localhost ~]# ls -l /dev/cdrom
    ls: cannot access /dev/cdrom: No such file or directory

No mention of cdrom device in `boot.log` as well. 

If I use the same VHD to create a VM using a storage account, it does appear.

**Comment by yuxisun1217** [comment] 2017-04-20 11:28
Hi @ecgg ,

Thank you for providing details.

Sorry I cannot reproduce it now. I created a managed disk sourced RHEL-7.3 VM in Resource Manager mode(West Europe, Standard_DS1, SSD) and it provisioned well. The /dev/cdrom existed.

My steps:(all in resource manager mode)
1. Prepare a RHEL-7.3 VHD in a storage blob with WALA-2.2.4-1 installed. 
2. In the Azure portal, create an image base on it.
3. Create a VM base on this image. The managed disk is "yes".

As you said, if put this VHD into a storage account and created a VM it worked well. So it seems shouldn't be hyperv driver or WALA issue.

**Comment by ecgg** [comment] 2017-04-20 12:13
Hi @yuxisun1217 

Thank you for verifying

Just a question - how did you generate the disk image you uploaded?

I tried the same, create managed disk via the Azure portal -where it interestingly enough asks me for which OS this will be. Then I create a VM using the az cli but the result was the same: no provisioning and errors about /dev/cdrom

**Comment by yuxisun1217** [comment] 2017-04-25 09:49
Hi @ecgg ,

Sorry for replying late. I created an on-demand VM first and copied the OS disk to another storage account. Then created an image and did the following things. I'll upload my own VHD and try it again. 

Best regards,
Yuxin Sun

**Comment by yuhuijiang** [comment] 2017-04-26 16:01
Hi @ecgg ,

I have tryed to reproduce the issue,but I didn't.Could you please provide extra informations to help me?
1) the command which you create the managed disk vm
2) the command which you create the image(if applicable)
3) some log file in the provisioning failed VM,/var/log/message,/var/log/dmesg

Thank you very much!

Regards,
Yuhui Jiang

**Comment by ecgg** [comment] 2017-04-27 04:21
Hi,

1. Commands issued via az cli to create managed disk + VM

```
az disk create                  \
--resource-group default            \
--name test-os.vhd             \
--location westeurope \
--sku Standard_LRS              \
--source https://defaultwestore.blob.core.windows.net/images/rhel7.3.vhd

DISK_ID=$(az disk show           \
--resource-group default            \
--name test-os.vhd             \
--query 'id'                    \
--output tsv)

az network nic create           \
--resource-group default            \
--name test-nic                \
--location westeurope \
--vnet-name default-we-vnet   \
--subnet MainSubnet

az vm create                    \
--resource-group default           \
--name test                    \
--nics test-nic                \
--location westeurope \
--os-type Linux                 \
--attach-os-disk $DISK_ID  \
--size Standard_DS1             \
--authentication-type password  \
--admin-username clouduser        \
--admin-password 'xxx' 
```

2 Commands how I created the image

I create a VM in KVM, using a kickstart file

```
virt-install \
--connect qemu:///system \
--name rhel7.3 \
--vcpus 2 \
--memory 2048 \
--disk /home/myuser/virt/images/rhel7.3.raw,size=32,format=raw,bus=virtio \
--network network:default \
--os-variant rhel7 \
--location=/home/myuser/Downloads/Software/ISO/rhel-server-7.3-x86_64-boot.iso \
--extra-args='ks=http://192.168.122.1/7.3.ks'
```

Then after install I prepare the disk image

```
PREFIX=$1

RAW=${PREFIX}.raw
VHD=${PREFIX}.vhd

# Round up to nearest MB
MB=$((1024 * 1024))
size=$(qemu-img info -f raw --output json "$RAW" | gawk 'match($0, /"virtual-size": ([0-9]+),/, val) {print val[1]}')
rounded_size=$((($size/$MB + 1) * $MB))
echo "rounded size = $rounded_size"
qemu-img resize -f raw $RAW $rounded_size

# convert to Fixed VHD
qemu-img convert -f raw -o subformat=fixed,force_size -O vpc $RAW $VHD
```

And upload it

```
FILE=$1

RG=default
SA=defaultwestore

export AZURE_STORAGE_CONNECTION_STRING=`azure storage account connectionstring show -g $RG $SA --json | jq -r .string`
azure storage blob upload --blobtype page --account-name $SA --container images $FILE
```

3. Log file- attached
[waagent.log.txt](https://github.com/Azure/WALinuxAgent/files/960425/waagent.log.txt)

**Comment by yuhuijiang** [comment] 2017-04-27 12:12
Hi @ecgg ,

Thanks for your informations.
According to your information, I successfully reproduced the issue.
The reason is the parameter "az vm create --attach-os-disk".If use this parameter to provide os disk,the VM will doesn't exist /dev/sr0 device,whether the os disk is a managed disk or unmanaged disk.

create a VM with unmanaged disk
> az vm create                    \
--resource-group $default           \
--name ${vmname}                  \
--location ${location} \
--os-type Linux                 \
--attach-os-disk   \ https://walayjg300disks839.blob.core.windows.net/vhds/walayjg30020170427192900.vhd \
--size Standard_DS1             \
--authentication-type password  \
--admin-username yujiang        \
--admin-password '*****' \
--use-unmanaged-disk 

create a VM with managed disk

> az vm create                    \
--resource-group $default           \
--name ${vmname}                  \
--location ${location} \
--os-type Linux                 \
--attach-os-disk walayjg-disk  \
--size Standard_DS1             \
--authentication-type password  \
--admin-username yujiang        \
--admin-password '******'


Maybe this parameter's design intention is used for specilized(have provisioned) image.So with this parameter,Azure platform will not provide /dev/sr0 to VM. This is just my guess.
So,we can wait for an  official explaination from MSFT side.
Thank you!






br,
Yuhui Jiang

**Comment by ecgg** [comment] 2017-04-27 13:05
Hi @yuhuijiang 

Thanks for digging! I'll follow up with Microsoft on my side and inform you when I have news.

**Comment by brendandixon** [comment] 2017-05-12 16:51
@ecgg Is there an issue here we need to address?

**Comment by brendandixon** [comment] 2017-05-18 21:41
@ecgg I am going to close this issue. If a problem persists, please re-open or open a new issue with sufficient details for us to address. Thank you.

**Closed by brendandixon** 2017-05-18 21:41 UTC

**Comment by ecgg** [comment] 2017-05-19 04:39
Hi,

Sorry for the delay - I was off work

Reply from microsoft:

"--attach-os-disk by design does not attach the ISO as it is only used for a specialized VHD where nothing is changed in the guest during provisioning"

So it is by design. You can close this. Thank you for your time.

Gregory



On Thu, 2017-05-18 at 14:41 -0700, brendandixon wrote:

@ecgg<https://github.com/ecgg> I am going to close this issue. If a problem persists, please re-open or open a new issue with sufficient details for us to address. Thank you.
