### ISSUE TITLE
[BUG] Problem using Deprovision with Extension

### ISSUE THREAD

**Issue by jlongo62** [Azure/WALinuxAgent#1792] opened 2020-02-26 22:21 UTC
I am attempting to deprovision a VM using the **CustomScript** extension and **waagent**.
When running the extension the Extension goes into "**Transioning**" state and is stuck there.

From watching the machine, it looks like _Deprovision_ works -- too well.
After the command processes, all accounts are gone and the VM will not allow any actions.., like examining logs.

I think what may be needed as a work around is a "ShutDown" argument for waagent to process upon removing accounts -- assuming waagent can still shutdown the machine after all accounts are removed OR perhaps waagent can load the deprovision to happen at machine shutdown and then shut it down. OR maybe I am just doing this wrong. I am sure someone has already made this work in the Linux world.

On windows SysPrep can Shutdown a machine after doing it's job.

Apply Extension (C#):
```
            var cmd = "sh Deprovision.sh";
            var result = vm.Update()
                        .DefineNewExtension("deprovision")
                        .WithPublisher("Microsoft.Azure.Extensions")
                        .WithType("CustomScript")
                        .WithVersion("2.1")
                        .WithMinorVersionAutoUpgrade()
                        .WithPublicSetting("fileUris", new string[] { blobUri })
                        .WithPublicSetting("commandToExecute", cmd)
                        .Attach()
                        .Apply();
```
The script is:
`sudo waagent -deprovision+user -verbose -force`

**Comment by pgombar** [comment] 2020-02-27 21:59
@jlongo62 running the deprovision command within Custom Script (or any extension, for that matter) will not work. There is a dependency between the agent and the extensions where the agent waits on the extensions to finish.

You would need to run the deprovision command from inside the VM. If you need to do this across multiple VMs, you might be able to set up a cron job that does this for you, using Custom Script. 

If your goal is getting a generalized image, you could use [packer](https://packer.io/).

Does that fit your use case?

**Comment by jlongo62** [comment] 2020-02-28 02:51
Not really...  we should be able to deprovision using the built in Azure features such as CustomScript extension or similar.

**Comment by pgombar** [comment] 2020-07-13 18:24
Hey @trstringer do you have any more ideas how this could be done? If not, I will close it "by design". Thanks!

**Comment by trstringer** [comment] 2021-01-21 16:45
Thanks for looping me in, and apologies for the delay. No I do not have any other ideas how else this could be done. Closing this as "by design".

**Closed by trstringer** 2021-01-21 16:45 UTC
Labels: provisioning, triaged
