### ISSUE TITLE
Microsoft.OSTCExtensions.LinuxDiagnostic extension failing:  libglibmm-2.4.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kiratp** [Azure/WALinuxAgent#150] opened 2016-02-03 22:36 UTC
On a fresh 15.10 VM, none of my portal metrics are working ("no data") and installing the OSPatching extension fails.
```

>azure vm extension set VmRG VmName OSPatchingForLinux Microsoft.OSTCExtensions 2.0 --public-config-path public.json
info:    Executing command vm extension set
+ Looking up the VM "VmName"
+ Installing extension "OSPatchingForLinux", VM: "VmName"
error:   Long running operation failed with error: 'VM has reported a failure when processing extension 'Microsoft.Insights.VMDiagnosticsSettings'. Error message: "mdsd stopped:MDSD crash:/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.0.92/mdsd/mdsd: error while loading shared libraries: libglibmm-2.4.so.1: cannot open shared object file: No such file or directory
".'.
info:    Error information has been recorded to C:\Users\localuser\.azure\azure.err
error:   vm extension set command failed
```

OS: Ubuntu  15.10 (Azure image)

**Comment by ShadowXVII** [comment] 2016-02-07 12:11
Duplicating #148

**Comment by ahmetalpbalkan** [comment] 2016-05-26 18:01
Closing as duplicate of #148.

**Closed by ahmetalpbalkan** 2016-05-26 18:01 UTC
Labels: duplicate
