### ISSUE TITLE
Creating a swap file takes too long

### ISSUE THREAD

**Issue by akorchemniy** [Azure/WALinuxAgent#116] opened 2015-10-20 19:09 UTC
I have an OpenLogic 7.1 VM with a waagent.conf for a swap disk:
`ResourceDisk.SwapSizeMB=16384`

When the machine starts up I notice that it takes >30 minutes to create the file.
`dd if=/dev/zero of=/mnt/resource/swapfile bs=1024 count=16777216`

Why not use fallocate? It's nearly instantaneous.

**Comment by yuezh** [comment] 2015-10-21 01:57
Hi, Alexandr 

That's a good suggestion. We will consider to use fallocate in our next release.

Thanks
Yue

**Comment by hglkrijger** [comment] 2016-05-25 23:32
duplicate of #127 - closing this instance

**Closed by hglkrijger** 2016-05-25 23:32 UTC
