### ISSUE TITLE
/var/lib/waagent keeps filling up with zip files

### ISSUE THREAD

**Issue by johanburati** [Azure/WALinuxAgent#1730] opened 2019-12-06 03:35 UTC
**/var/lib/waagent** keeps filling up with zip files.

Users reported issues with VM not booting up because of **/var** being full (https://github.com/microsoft/OMS-Agent-for-Linux/issues/932)
This issue has already been reported before (https://github.com/Azure/WALinuxAgent/issues/1020 ) and is still occuring with the latest version.

Is there any reason why **waagent** keeps all those old zip files ? Would it be possible to add some code to delete those old files ?

## EXAMPLE
```
-rw-r--r-- 1 root root 126056109 Aug  7 09:54 Microsoft.Azure.Diagnostics__LinuxDiagnostic__3.0.121.zip
-rw-r--r-- 1 root root 142397246 Nov  3 11:05 Microsoft.Azure.Diagnostics.LinuxDiagnostic__3.0.125.zip
-rw-r--r-- 1 root root   1374378 Feb  3  2018 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9126.0.zip
-rw-r--r-- 1 root root   1375184 Feb 16  2018 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9127.0.zip
-rw-r--r-- 1 root root   1374020 Mar  6  2018 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9128.0.zip
-rw-r--r-- 1 root root   1393624 Apr 20  2018 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9131.0.zip
-rw-r--r-- 1 root root   1394887 May 30  2018 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9133.0.zip
-rw-r--r-- 1 root root   1401585 Jul 30  2018 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9136.0.zip
-rw-r--r-- 1 root root   1439101 Feb 12  2019 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9146.0.zip
-rw-r--r-- 1 root root   1439094 Feb 24  2019 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9147.0.zip
-rw-r--r-- 1 root root   1438804 Apr 10  2019 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9148.0.zip
-rw-r--r-- 1 root root   1438571 Apr 15  2019 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9149.0.zip
-rw-r--r-- 1 root root   1438703 May 10  2019 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9150.0.zip
-rw-r--r-- 1 root root   1440027 Aug 21 11:02 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9151.0.zip
-rw-r--r-- 1 root root   1442515 Sep 25 10:31 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9153.0.zip
-rw-r--r-- 1 root root   1448436 Oct  3 10:44 Microsoft.Azure.RecoveryServices__VMSnapshotLinux__1.0.9156.0.zip
-rw-r--r-- 1 root root   2350933 Mar 25  2018 Microsoft.CPlat.Core__RunCommandLinux__1.0.0.zip
-rw-r--r-- 1 root root 113383928 May  5  2019 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.10.3.zip
-rw-r--r-- 1 root root 113384304 May 14  2019 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.10.5.zip
-rw-r--r-- 1 root root 129614911 Jul 27 10:52 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.11.15.zip
-rw-r--r-- 1 root root 129728388 Jun 11 10:33 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.11.3.zip
-rw-r--r-- 1 root root 129742348 Jun 19 10:30 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.11.5.zip
-rw-r--r-- 1 root root 129742423 Jun 25 10:50 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.11.7.zip
-rw-r--r-- 1 root root 129628554 Jun 28 10:40 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.11.9.zip
-rw-r--r-- 1 root root 140756004 Dec  6 08:12 Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux__1.12.15.zip
-rw-r--r-- 1 root root 137303839 Oct 17 10:44 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.12.1.zip
-rw-r--r-- 1 root root 137317799 Oct 21 11:13 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.12.5.zip
-rw-r--r-- 1 root root 118059938 Mar  3  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.59.1.zip
-rw-r--r-- 1 root root 115012056 Mar  8  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.60.2.zip
-rw-r--r-- 1 root root 112370654 Jan 31  2019 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.8.12.zip
-rw-r--r-- 1 root root 113049744 Feb 22  2019 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.9.1.zip
-rw-r--r-- 1 root root    478290 Apr 24  2019 WALinuxAgent-2.2.40.zip
-rw-r--r-- 1 root root    486628 Jul  4 05:34 WALinuxAgent-2.2.41.zip
-rw-r--r-- 1 root root    506986 Aug 13 09:48 WALinuxAgent-2.2.42.zip
-rw-r--r-- 1 root root    502139 Oct 25 10:55 WALinuxAgent-2.2.44.zip
-rw-r--r-- 1 root root    517593 Nov 19 08:14 WALinuxAgent-2.2.45.zip
```

## VERSION
```
WALinuxAgent-2.2.35.1 running on oracle 7.6
Python: 2.7.5
Goal state agent: 2.2.45
```

**Comment by vrdmr** [comment] 2019-12-06 06:01
Hi @johanburati, Thanks for reporting.

There were changes made in #1431 which prevented the redownload of the zip packages, especially for a failed update scenario. This surfaced a new issue that was not deleting already downloaded zip packages - which is what you are seeing.

#1642 solves the issue for newer agents and [newer format](https://github.com/Azure/WALinuxAgent/pull/1642/files#diff-f8c44add0bc67ec987eff75282ec2308R1364-R1368) of the zip file names that we use now. Based on the dates of the zip files you mention, they look like from old format pattern. The quick mitigation for you would be to delete the zips.

I'll see if I can add another pattern check to remove all the old patterns as well.

**Comment by sbonds** [comment] 2019-12-13 17:36
Does this fix clean up only WALinuxAgent-* or will it cover sub-agents like Microsoft.Azure.Diagnostics* also?

**Comment by johanburati** [comment] 2019-12-16 06:19
https://github.com/Azure/WALinuxAgent/pull/1642 cleans up the **extension** zip files that have the *new format*.

New format: `Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux__1.12.15.zip`
Old format: `Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.11.9.zip`

Please refer to the listing above you will see that you have multiple files with the *old format* for one extension, please delete those files manually if you need the space, going forward all the extension files will have the *new format* and the agent will take care of deleting them.

**Comment by pgombar** [comment] 2020-06-23 23:26
Issue is resolved with #1642 and zip files will not keep accumulating anymore. If you have old zips laying around, the mitigation is to manually delete them, they won't come back.

**Closed by pgombar** 2020-06-23 23:26 UTC
Labels: triaged

**Comment by etcetc** [comment] 2022-03-08 16:47
Does this also apply to files for SiteRecovery such as Microsoft.Azure.RecoveryServices.SiteRecovery__Linux__1.0.0.9119.zip ?  OK to manually delete all .zip files?

**Comment by larohra** [comment] 2022-03-08 17:28
@etcetc is this the only `Microsoft.Azure.RecoveryServices.SiteRecovery__Linux__*.zip` file in your VM? Or do you have multiple versions installed in there? Having 1 is by design, having multiple is wrong. If you have multiple, you can keep the latest one and delete the older ones. If you just have one, you can delete it but the guest agent might re-download it somewhere down the line as per design.

Hope that helps!

**Comment by etcetc** [comment] 2022-03-08 18:11
oops - already deleted them.  Most had dates pre 2019 so I suspect they were leftovers from pre-resolution

**Comment by OmkarSangote** [comment] 2023-01-02 08:24
> Hi @johanburati, Thanks for reporting.
> 
> There were changes made in #1431 which prevented the redownload of the zip packages, especially for a failed update scenario. This surfaced a new issue that was not deleting already downloaded zip packages - which is what you are seeing.
> 
> #1642 solves the issue for newer agents and [newer format](https://github.com/Azure/WALinuxAgent/pull/1642/files#diff-f8c44add0bc67ec987eff75282ec2308R1364-R1368) of the zip file names that we use now. Based on the dates of the zip files you mention, they look like from old format pattern. The quick mitigation for you would be to delete the zips.
> 
> I'll see if I can add another pattern check to remove all the old patterns as well.

Are there any script written to identify and remove all the old patterns?

**Comment by narrieta** [comment] 2023-01-03 00:41
@OmkarSangote You can remove all the zip files under /var/lib/waagent.

**Comment by OmkarSangote** [comment] 2023-01-03 05:12
> @OmkarSangote You can remove all the zip files under /var/lib/waagent.

In a wholistic way I feel that deleting the files manually may cause other issues, so it is recommend that a script can be used to remove older zip files, since I have multiple systems.

**Comment by narrieta** [comment] 2023-01-03 14:47
Yes, you can write a script to this. It's as simple as "rm -f /var/lib/waagent/*.zip". That won't cause other issues in the agent.
