### ISSUE TITLE
v2.2.11 - questionable split() call in "common/conf.py"

### ISSUE THREAD

**Issue by u6006** [Azure/WALinuxAgent#714] opened 2017-05-14 21:29 UTC
- Waagent version (cloned on 05/14/2017)
grep "^AGENT_VERSION = " common/version.py 
AGENT_VERSION = '2.2.11'

- Is there any special consideration for the following split() call at line #43? or else it cannot handle spaces in the value 'k=" v"' or 'k="v0 v1"' (in common/conf.py)
 41         for line in content.split('\n'):
 42             if not line.startswith("#") and "=" in line:
 43                 parts = line.split()[0].split('=')
 44                 value = parts[1].strip("\" ")

**Comment by brendandixon** [comment] 2017-05-15 16:08
@u6006 I'm not seeing what you're seeing. Could you provide a concrete example that fails? Admittedly, this is very simple parsing code. It is not intended to be, as with most Unix-style configuration files, a general purpose, able to handle all kinds of strings, parser. It is intended to handle only the most basic cases. If you can provide a legitimate failure, we'll gladly fix it.

**Comment by u6006** [comment] 2017-05-15 16:39
the code on line 43 splits the input line by spaces first, so chars after the 1st space was filtered out by "line.split()[0]...", as such, the two examples posted above will fail to be parsed

k=" v" will get empty value
k="v0 v1" will get 'v0' as the value (it can be space separated words)

If it's intentional, it's not a bug (but the comment should be added to clarify), or else it should be refactored to cover the cases that I listed.

**Comment by brendandixon** [comment] 2017-05-15 16:54
@u6006 Got it. The latter case is not a bug as spaces are not allowed in all valid values. However, the first case should be addressed. I believe the best change is to remove the initial split from line #43.

**Comment by u6006** [comment] 2017-05-15 17:44
Agree. Removing the 1st split() will handle both my cases though the latter is not supported.

**Comment by brendandixon** [comment] 2017-05-24 20:27
Fixed by #729.

**Closed by brendandixon** 2017-05-24 20:27 UTC
