### ISSUE TITLE
issue with waagent 2.0.13

### ISSUE THREAD

**Issue by jimbeauh** [Azure/WALinuxAgent#1247] opened 2018-07-10 14:02 UTC
With waagent version, we are seeing the following errors:

Waagent - 2018/07/03 11:06:27 ERROR:  File "/asa/scripts/waagent", line 6466, in main
Waagent - 2018/07/03 11:06:27 ERROR:    WaAgent.Run()
Waagent - 2018/07/03 11:06:27 ERROR:  File "/asa/scripts/waagent", line 6043, in Run
Waagent - 2018/07/03 11:06:27 ERROR:    goalState.ExtensionsConfig.ReportHandlerStatus()
Waagent - 2018/07/03 11:06:27 ERROR:  File "/asa/scripts/waagent", line 4274, in ReportHandlerStatus
Waagent - 2018/07/03 11:06:27 ERROR:    status='{"version":"1.0","timestampUTC":"'+tstamp+'","aggregateStatus":{"guestAgentStatus":{"version":"'+GuestAgentVersion+'","status":"'+agent_state+'","formattedMessage":{"lang":"en-US","message":"'+agent_msg+'"}},"handlerAggregateStatus":['+statuses+']}}'
Waagent - 2018/07/03 11:06:27 ERROR:TypeError: cannot concatenate 'str' and 'int' objects
Waagent - 2018/07/03 11:06:27 ERROR:
Waagent - 2018/07/03 11:06:27 ERROR:Exception: cannot concatenate 'str' and 'int' objects
azure_waagent_startup.sh:  Restarting waagent
Waagent - 2018/07/03 11:06:32 Windows Azure Linux Agent Version: WALinuxAgent-2.0.13

I  realize that this is below the minimum waagent version, but we have customers running ASAv and FTDv VMs that use this version. Something must have recently changed in Azure to cause this issue. It is blocking customer deployments.

Thanks...Jim Holland

**Comment by danielsollondon** [comment] 2018-07-10 23:12
closing - being worked on by sz

**Closed** 2018-07-12 04:22 UTC

**Comment by colmerts** [comment] 2019-03-14 00:05
Hi Jim, what was the result of this please?  I'm dealing with the same issue. 

Thanks,
Colin

**Comment by jimbeauh** [comment] 2019-03-14 13:51
Colin,

The issue turned out to not be related to the waagent, but some other Azure infrastructure change that made it so that our VM/application was unable to access storage. We worked closely with the Azure Linux team but never found the root cause.

jim

**Comment by colmerts** [comment] 2019-03-14 14:58
Many thanks Jim.

On 14 Mar 2019, at 13:51, jimbeauh <notifications@github.com> wrote:

Colin, 

The issue turned out to not be related to the waagent, but some other Azure infrastructure change that made it so that our VM/application was unable to access storage. We worked closely with the Azure Linux team but never found the root cause. 

jim
