### ISSUE TITLE
[BUG] RunPowerShellScript execution hangs while deprovisioning Linux VM with waagent

### ISSUE THREAD

**Issue by abaymar** [Azure/WALinuxAgent#2006] opened 2020-09-10 21:54 UTC
**RunPowerShellScript hangs while executing 'sudo waagent -deprovision+user -force'**

I want to be able to deprovision a VM from Azure Runbook. I'm using PowerShell as follows:

```
$restUri = 'https://management.azure.com/subscriptions/'+ $azContext.Subscription.Id+'/resourceGroups/'+$resourceGroupName+ `
    '/providers/Microsoft.Compute/virtualMachines/'+$VMName+'/runCommand?api-version=2017-03-30'
$body = @{
  'commandId' = 'RunShellScript'
  'script' = @('sudo waagent -deprovision+user -force')
}
$response = Invoke-webrequest -Uri $restUri -Method Post -Headers $authHeader -Body $($body | ConvertTo-Json)

$asyncstatus = $($response.headers.'Azure-AsyncOperation')
$status = "InProgress"
While($status -eq "InProgress")`
{
  Write-Output "Status: $status"
  $response = invoke-webrequest -uri $asyncstatus -Headers $authHeader
  $status = $($response.Content | ConvertFrom-Json).status -eq "InProgress"
  sleep 5
}

Write-Output $($response.Content | ConvertFrom-Json).properties.output.message
```

**Observed behavior:** the user is deprovisioned, but the REST API call never completes so I keep getting "InProgress" every 5 seconds until the Runbook token times out.
**Expected behavior:** the REST API call completes once the user is deprovisioned.

**Note:** same call ('sudo waagent -deprovision+user -force') completes OK when run via SSH.

 - Distro and Version: Ubuntu 18.04 LTS

**Comment by abaymar** [comment] 2020-09-11 10:45
Might be a duplicate of #1792

**Comment by abaymar** [comment] 2020-09-11 16:33
As a workaround, my script is setting up a cronjob for deprovisioning instead of directly calling waagent.

**Comment by narrieta** [comment] 2020-09-15 03:09
@abaymar Yes, it is a duplicate of #1792. Closing this one. Also, as pointed out in #1792, this is currently not supported.

**Closed by narrieta** 2020-09-15 03:09 UTC
Labels: provisioning, triaged

**Comment by narrieta** [comment] 2020-09-15 16:28
@abaymar Yes, agreed. We have a work item for this in our queue, but at this point we are focused on other tasks. Once we get to it I'll post to #1792

**Comment by o-l-a-v** [comment] 2020-11-05 17:16
> @narrieta would be good if the API call failed gracefully instead of hanging

Your while loop is flawed.

```powershell
 $status = $($response.Content | ConvertFrom-Json).status -eq "InProgress"
```

will give a boolean, so makes no sense to check if 

```powershell
While($status -eq "InProgress")
```

**Comment by abaymar** [comment] 2020-11-06 16:20
@o-l-a-v you are correct - thank you for pointing out
