### ISSUE TITLE
WaLinuxAgent does not support mixed case hostnames in RHEL based distros

### ISSUE THREAD

**Issue by asofron** [Azure/WALinuxAgent#1413] opened 2018-12-03 11:42 UTC
Seems that issue #686  is still not fixed and WaLinuxAgent will change mixed case hostnames to lowercase . 

Repo steps:

- Provision a new CentOS 7.5 VM from marketplace
- name vm TEST-LOWER-host-123 (capitalized)
- SSH into VM
- Expect behavior: VM name is TEST-LOWER-host-123
- Actual behavior: VM name is test-lower-host-123

Relevant log information : 

2018/11/29 06:18:09.074530 INFO Azure Linux Agent Version:2.2.18
2018/11/29 06:18:09.102975 INFO OS: centos 7.5.1804
2018/11/29 06:18:09.124760 INFO Python: 2.7.5
2018/11/29 06:18:09.144067 INFO Run daemon
2018/11/29 06:18:09.165500 INFO Activate resource disk
2018/11/29 06:18:09.199877 INFO Examining partition table
2018/11/29 06:18:09.634732 INFO GPT not detected, determining filesystem
2018/11/29 06:18:09.840006 INFO sfdisk with --part-type failed [1], retrying with -c
2018/11/29 06:18:09.877372 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/11/29 06:18:09.906620 INFO The partition is formatted with ntfs, updating partition type to 83
2018/11/29 06:18:09.947565 INFO sfdisk with --part-type failed [1], retrying with -c
2018/11/29 06:18:09.998457 INFO sfdisk -c  /dev/sdb 1 83 succeeded
2018/11/29 06:18:10.049946 INFO Format partition [mkfs.ext4 -F /dev/sdb1]
2018/11/29 06:18:14.321048 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2018/11/29 06:18:14.556606 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2018/11/29 06:18:14.594610 INFO Clean protocol
2018/11/29 06:18:14.614026 INFO Running default provisioning handler
2018/11/29 06:18:14.647040 INFO Copying ovf-env.xml
2018/11/29 06:18:14.780745 INFO Successfully mounted dvd
2018/11/29 06:18:15.235163 INFO Detect protocol by file
2018/11/29 06:18:15.263746 INFO Clean protocol
2018/11/29 06:18:15.286679 INFO WireServer endpoint is not found. Rerun dhcp handler
2018/11/29 06:18:15.427930 INFO Fabric preferred wire protocol version:2015-04-05
2018/11/29 06:18:15.469442 INFO Wire protocol version:2012-11-30
2018/11/29 06:18:15.496353 WARNING Server preferred version:2015-04-05
2018/11/29 06:18:19.839485 INFO Starting provisioning
2018/11/29 06:18:19.863363 INFO Handle ovf-env.xml.
**2018/11/29 06:18:19.885538 INFO Set hostname [TEST-LOWER-host-123]
2018/11/29 06:18:19.977846 INFO Publish hostname [TEST-LOWER-host-123]**
2018/11/29 06:18:20.748139 INFO Examine /proc/net/route for primary interface
2018/11/29 06:18:20.773030 INFO Primary interface is [eth0]
2018/11/29 06:18:20.791206 INFO interface [lo] has flags [73], is loopback [True]
2018/11/29 06:18:20.816106 INFO Interface [lo] skipped
2018/11/29 06:18:20.833318 INFO interface [eth0] has flags [4163], is loopback [False]
2018/11/29 06:18:20.860918 INFO Interface [eth0] selected
2018/11/29 06:18:20.902616 INFO Examine /proc/net/route for primary interface
2018/11/29 06:18:20.926637 INFO Primary interface is [eth0]
2018/11/29 06:18:20.944233 INFO interface [lo] has flags [73], is loopback [True]
2018/11/29 06:18:20.967505 INFO Interface [lo] skipped
2018/11/29 06:18:20.983927 INFO interface [eth0] has flags [4163], is loopback [False]
2018/11/29 06:18:21.008764 INFO Interface [eth0] selected
2018/11/29 06:18:23.471078 INFO Create user account if not exists
2018/11/29 06:18:23.835881 INFO Set user password.
2018/11/29 06:18:23.963087 INFO Configure sudoer
2018/11/29 06:18:23.985264 INFO Configure sshd
2018/11/29 06:18:24.005352 INFO Enabled SSH password-based authentication methods.
2018/11/29 06:18:24.039285 INFO Configured SSH client probing to keep connections alive.
2018/11/29 06:18:24.226616 INFO Event: name=WALinuxAgent, op=Provision, message=Provision succeed, duration=9612
2018/11/29 06:18:26.313530 INFO Provisioning complete
2018/11/29 06:18:26.337623 INFO RDMA capabilities are not enabled, skipping
2018/11/29 06:18:26.371206 INFO Installed Agent WALinuxAgent-2.2.18 is the most current agent
2018/11/29 06:18:26.554466 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
2018/11/29 06:18:26.621509 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
2018/11/29 06:18:26.657309 INFO Start env monitor service.
2018/11/29 06:18:26.682103 INFO Configure routes
2018/11/29 06:18:26.702676 INFO Gateway:None
2018/11/29 06:18:26.722235 INFO Routes:None
2018/11/29 06:18:26.778503 INFO WALinuxAgent-2.2.18 running as process 1366
2018/11/29 06:18:26.819019 INFO Event: name=WALinuxAgent, op=AutoUpdate, message=, duration=0
2018/11/29 06:18:26.983933 INFO Set block dev timeout: sda with timeout: 300
2018/11/29 06:18:27.021800 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.20 downloaded successfully, duration=0
2018/11/29 06:18:27.027177 INFO Set block dev timeout: sdb with timeout: 300
2018/11/29 06:18:27.189311 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.25 downloaded successfully, duration=0
2018/11/29 06:18:27.290266 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.26 downloaded successfully, duration=0
2018/11/29 06:18:27.380846 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.31 downloaded successfully, duration=0
2018/11/29 06:18:27.484882 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.32.2 downloaded successfully, duration=0
2018/11/29 06:18:27.693888 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.33 downloaded successfully, duration=0
2018/11/29 06:18:27.789148 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.34 downloaded successfully, duration=0
2018/11/29 06:18:27.842521 INFO Agent WALinuxAgent-2.2.18 discovered WALinuxAgent-2.2.34 as an update and will exit
2018/11/29 06:18:28.466118 INFO Agent WALinuxAgent-2.2.18 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running
2018/11/29 06:18:28.525202 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.18 launched with command 'python -u /usr/sbin/waagent -run-exthandlers' is successfully running, duration=0
2018/11/29 06:18:28.605323 INFO Determined Agent WALinuxAgent-2.2.34 to be the latest agent
2018/11/29 06:18:28.744992 INFO ExtHandler Agent WALinuxAgent-2.2.34 is running as the goal state agent
2018/11/29 06:18:28.907861 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent
2018/11/29 06:18:28.945906 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/memory/WALinuxAgent
2018/11/29 06:18:28.986509 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/cpu/WALinuxAgent/WALinuxAgent
2018/11/29 06:18:29.029291 INFO ExtHandler Creating cgroup directory /sys/fs/cgroup/memory/WALinuxAgent/WALinuxAgent
2018/11/29 06:18:29.081636 INFO ExtHandler Start env monitor service.
2018/11/29 06:18:29.120885 INFO ExtHandler Configure routes
2018/11/29 06:19:41.805142 INFO Agent WALinuxAgent-2.2.18 forwarding signal 15 to WALinuxAgent-2.2.34
2018/11/29 06:20:19.743200 INFO Azure Linux Agent Version:2.2.18
2018/11/29 06:20:19.858043 INFO OS: centos 7.5.1804
2018/11/29 06:20:19.935022 INFO Python: 2.7.5
2018/11/29 06:20:19.989184 INFO Run daemon
2018/11/29 06:20:20.039130 INFO Activate resource disk
2018/11/29 06:20:20.116441 INFO Examining partition table
2018/11/29 06:20:20.191605 INFO GPT not detected, determining filesystem
2018/11/29 06:20:20.253988 INFO sfdisk with --part-type failed [1], retrying with -c
2018/11/29 06:20:20.354176 INFO sfdisk -c -f /dev/sdb 1 -n succeeded
2018/11/29 06:20:20.397249 INFO The partition type is 83
2018/11/29 06:20:20.455135 INFO Mount resource disk [mount /dev/sdb1 /mnt/resource]
2018/11/29 06:20:20.823384 INFO Resource disk /dev/sdb is mounted at /mnt/resource with ext4
2018/11/29 06:20:20.861276 INFO Clean protocol
2018/11/29 06:20:20.883776 INFO Provisioning already completed, skipping.
2018/11/29 06:20:20.911389 INFO RDMA capabilities are not enabled, skipping
2018/11/29 06:20:20.957074 INFO Determined Agent WALinuxAgent-2.2.34 to be the latest agent
2018/11/29 06:20:21.105022 INFO ExtHandler Agent WALinuxAgent-2.2.34 is running as the goal state agent
**2018/11/29 06:20:23.009926 INFO ExtHandler EnvMonitor: Detected hostname change: TEST-LOWER-host-123 -> test-lower-host-123**
2018/11/29 06:20:23.213522 INFO ExtHandler Examine /proc/net/route for primary interface
2018/11/29 06:20:23.287959 INFO ExtHandler Primary interface is [eth0]
2018/11/29 06:20:23.356237 INFO ExtHandler Examine /proc/net/route for primary interface
2018/11/29 06:20:23.391338 INFO ExtHandler Primary interface is [eth0]
2018/11/29 06:20:25.875504 INFO ExtHandler EnvMonitor: Detected dhcp client restart. Restoring routing table.
2018/11/29 06:20:25.916739 INFO ExtHandler Configure routes
2018/11/29 06:20:25.935693 INFO ExtHandler Gateway:None

**Comment by iamshital** [comment] 2019-02-26 13:19
@narrieta  Any updated on this?

**Comment by narrieta** [comment] 2019-10-15 23:08
@trstringer could you take a look at this one? thanks

**Comment by trstringer** [comment] 2019-10-16 14:25
@narrieta absolutely I'll check it out.

**Comment by taoyama** [comment] 2019-10-27 12:28
I believe this is not a bug.
The Domain Name System (DNS) names is case insensitive. Therefore we can not use mixed case hostnames in Azure.
https://github.com/Azure/WALinuxAgent/blob/develop/azurelinuxagent/ga/env.py#L140

This limitation is written in the [document](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances).
<code>
Host names must be DNS-compatible. Names must use only 0-9, a-z, and '-', and cannot start or end with a '-'.
</code>

**Comment by trstringer** [comment] 2020-01-03 22:09
I'm not sure that this is even possible at the moment. My attempts are reproducing the issue show that it has to be all lowercase:

> Azure Error: InvalidTemplateDeployment
Message: The template deployment '...' is not valid according to the validation procedure. The tracking id is '...'. See inner errors for details.
Exception Details:
        Error Code: InvalidDomainNameLabel
        Message: The domain name label ... is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.

I understand that this issue is quite old, so I'm going to close this but if you are still running into the same problem currently please feel free to reopen the issue and provide additional repro steps. Thanks!

**Closed by trstringer** 2020-01-03 22:09 UTC
Labels: bug, provisioning, triaged
