### ISSUE TITLE
[BUG/Question] RHEL / CentOS 7 connection issue after hostname change if not using networkmanager

### ISSUE THREAD

**Issue by jpbuecken** [Azure/WALinuxAgent#1529] opened 2019-05-17 11:46 UTC
**Describe the bug**
We manage our RHEL / CentOS based instances without networkmanager. E.g. RHEL 5 (ELS), RHEL/CENTOS 6, RHEL/CENTOS 7.
We manage them OnPremise and in other private and public clouds beside AZURE in a great quantity.
Now the azure agent rpm has a dependency to the networkmanager on RHEL based instances.
We would like to use CentOS 7 from OpenLogic without networkmanager. So we stopped and masked the networkmanager service via systemd and configured the ifcfg-eth0 as usual without NM. Everything is working fine. But if we change the hostname, we get a strange network connection issue:
Outgoing connection only work in a few cases (e.g. test via curl)
Same for incoming connection: In a tcpdump we can see that the traffic reaches the server, but the server does not send an answer. But it is working in a few cases.
We checked iptables, routes, ip addr and could not identify the root cause.
Restart of network service did not help. We need to reboot. Then everything is fine again.

So we have three questions:
What is the root cause of this behaviour?
Will other action than change of  hostname lead to this behaviour?
How can we disable NetworkManager?

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: CentOS 7.6 from OpenLogic
 - WALinuxAgent version: 2.2.40

**Steps to reproduce:**
```
Boot CentOS 7.6 from OpenLogic
sudo sed -i s/NM_CONTROLLED=yes/NM_CONTROLLED=no/ /etc/sysconfig/network-scripts/ifcfg-eth0
sudo systemctl stop NetworkManager
sudo systemctl mask NetworkManager
reboot
sudo hostnamectl set-hostname mycustomname
for i in 1 2 3 4 5 6 7 8 9 10; do curl google.de; done
```

**Log of /var/log/waagent.log**
```
2019/05/17 11:44:56.289572 INFO ExtHandler EnvMonitor: Detected hostname change: XXXXXXXX -> mycustomname
2019/05/17 11:44:56.319606 ERROR ExtHandler Command: [service NetworkManager restart], return code: [1], result: [Redirecting to /bin/systemctl restart NetworkManager.service
Failed to restart NetworkManager.service: Unit is masked.
]
2019/05/17 11:44:56.321262 INFO ExtHandler Examine /proc/net/route for primary interface
2019/05/17 11:44:56.321892 INFO ExtHandler Primary interface is [eth0]
2019/05/17 11:44:56.342116 INFO ExtHandler Examine /proc/net/route for primary interface
2019/05/17 11:44:56.343796 INFO ExtHandler Primary interface is [eth0]
2019/05/17 11:44:58.712100 INFO ExtHandler EnvMonitor: Detected dhcp client restart. Restoring routing table.
2019/05/17 11:44:58.713924 INFO ExtHandler Configure routes
2019/05/17 11:44:58.714557 INFO ExtHandler Gateway:None
2019/05/17 11:44:58.715042 INFO ExtHandler Routes:None
```

Edit: Replaced original hostname in Log manually by XXXXXX

**Comment by yuxisun1217** [comment] 2019-06-21 09:36
Hi @buec011 ,

I followed your steps and saw error in network.service:
After "hostnamectl set-hostname walachecka" then "systemctl status network -l" I saw this message:
'''
Jun 21 17:26:09 walachecka dhclient[903]: receive_packet failed on eth0: Network is down
'''

This is the network service info:
'''
# systemctl status network -l
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: active (running) since Fri 2019-06-21 17:18:29 CST; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 703 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/network.service
           └─903 /sbin/dhclient -1 -q -lf /var/lib/dhclient/dhclient--eth0.lease -pf /var/run/dhclient-eth0.pid -H walacheck1 eth0
'''
My new hostname is "walachecka" but the dhclient -H is still "walacheck1" which is my old hostname. 
Then I restart network service and check status again:
'''
# systemctl status network -l
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; bad; vendor preset: disabled)
   Active: active (running) since Fri 2019-06-21 17:32:52 CST; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2512 ExecStop=/etc/rc.d/init.d/network stop (code=exited, status=0/SUCCESS)
  Process: 2675 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/network.service
           ├─ 903 /sbin/dhclient -1 -q -lf /var/lib/dhclient/dhclient--eth0.lease -pf /var/run/dhclient-eth0.pid -H walacheck1 eth0
           └─2875 /sbin/dhclient -1 -q -lf /var/lib/dhclient/dhclient--eth0.lease -pf /var/run/dhclient-eth0.pid -H walachecka eth0
'''
Here're 2 dhclient process and the wrong one is still there. Not sure if this is the root cause. Could you please try to kill the old dhclient process first and restart network service and check your traffic again?
I don't know how to hit the traffic issue(as you said the "curl" cannot hit the issue). Could you please provide some steps that can hit the traffic issue so that I can also have a try. Thanks!

**Comment by buec011** [comment] 2019-06-27 08:15
Hello @yuxisun1217 
> I don't know how to hit the traffic issue(as you said the "curl" cannot hit the issue). 
Maybe I explained it badly, but curl hits the issue. So please use curl to test.

But we already found that it has been fixed in latest kernel:
kernel-3.10.0-957.21.3.el7.x86_64 fixed,  
kernel-3.10.0-957.10.1.el7.x86_64 issue reproducable.

We believe this commit of the changelog fixed our bug:
- [netdrv] hv_netvsc: Fix a network regression after ifdown/ifup (Mohammed Gamal) [1679997 1661632]

A public bug here: https://github.com/coreos/bugs/issues/2454

The waagent only trigger the issue because it restarting the network.

So the only thing left is to build a new CentOS 7.6 image in azure by openlogic/rougewave with kernel-3.10.0-957.21.3.el7.x86_64 pre-installed.

**Comment by pgombar** [comment] 2020-07-13 18:11
Tracked here: coreos/bugs#2454 and seems to be fixed.

**Closed by pgombar** 2020-07-13 18:11 UTC
Labels: triaged
