### ISSUE TITLE
More descriptive logs when OS Provisioning failure occurs

### ISSUE THREAD

**Issue by mbearup** [Azure/WALinuxAgent#659] opened 2017-04-10 18:44 UTC
Should expose more detailed failure information so that VM deployers can clearly understand the reason for failure. Specifically it should identify if both cloud-init and waagent are both configured to handle provisioning, and log it appropriately.

**Comment by hglkrijger** [comment] 2017-04-10 19:27
@mbearup, is this a duplicate of #654?

**Closed** 2017-04-18 21:35 UTC
