### ISSUE TITLE
Cannot get to state 'Running' with Provisioning.Enabled=n 

### ISSUE THREAD

**Issue by jayninja** [Azure/WALinuxAgent#850] opened 2017-08-21 22:11 UTC
I've seen a few bugs in the past around this( #756  ). But it doesn't appear to be resolved. I am not using cloud-init, but I also don't want any users or extensions to be added to this VM. Per the documentation I set Provisioning.Enabled=n in the config.

Now, when I deploy the VHD, I am no longer able to reach the 'Running' state. It sits in 'Creating' until eventually reaching 'Failed'. I toggle Provisioning.Enabled=y and it works. I flip it back to 'n' and it fails again. 

I tried three things:
1. I used openlogics version: http://olcentgbl.trafficmanager.net/openlogic/6/openlogic/x86_64/RPMS/WALinuxAgent-2.2.14-1.el6.noarch.rpm. It exhibited the same problem.
2. I also cloned this repo, and rolled my own rpm. It had the same problem.
3. I rolled back to 2.0.18 from the openlogic repo, and **it worked** like a charm.

**Comment by brendandixon** [comment] 2017-08-21 22:20
@jayninja I do not know what documentation you may have read, but provisioning is required. The `Provisioning.Enabled` option exists mostly for historical reasons. Even captured images, after being prepared via de-provisioning, undergo provisioning.

Our upcoming release (2.2.15) relaxes these rules a bit and will report as "ready" VMs deployed from captured images that were not de-provisioned. This, I believe, will address your situation.

**Comment by jnoxon** [comment] 2017-08-21 22:22
How do you prevent the creation of users via the agent? I have an appliance image in the marketplace that uses Provisioning.Enabled=n to prevent user creation, but I cannot update the agent without a workaround.

**Comment by brendandixon** [comment] 2017-08-21 22:28
@jayninja If the user already exists, the agent will not modify it. I suggest you capture an image with the user created, but disabled. (There are several articles on the internet describing how to do this.) That should work for your uses.

**Comment by jnoxon** [comment] 2017-08-21 22:28
I need to prevent any user creation at all.

**Comment by brendandixon** [comment] 2017-08-21 22:29
@jayninja That is not an option I believe we support at present in Azure.

**Comment by jayninja** [comment] 2017-08-21 22:31
@brendandixon that actually isn't entirely correct. You DID support it. The functionality just changed out from under us, and now you are saying it isn't supported. It looks like @jnoxon has the same problem I do.

**Comment by brendandixon** [comment] 2017-08-21 22:34
@jayninja @jnoxon Hmm, as far as the *agent* code is concerned, it has *always* expected to add a user during provisioning. I've just checked several versions going back a number of years. I'm not sure what enabled creation without a user...

**Comment by jayninja** [comment] 2017-08-21 22:38
@brendandixon In the past we could (mis)use the Provisioning.Enabled directive to achieve this. It prevented users from being created, and extensions from being loaded. But we still got an IP and hostname monitoring,etc work just fine... 

From what you're saying the use of Provisioning.Enabled is evolving(or decaying?). However, that leaves us stuck with an edge-case for all people who have appliances in the marketplace.

**Comment by jnoxon** [comment] 2017-08-21 22:44
In my case, I have a marketplace offering where customers have no valid use case for accessing the instance directly. It is deployed into customer infrastructure, but managed through a separate service. Allowing users to easily create users & log into the VM is a huge problem.

In a past ticket I opened (https://github.com/Azure/WALinuxAgent/issues/550) someone referenced an "appliance model" which might work around this, but no details ever emerged.

What's the risk in keeping the VMs on 2.0.18 indefinitely?

**Comment by brendandixon** [comment] 2017-08-21 22:50
@jnoxon The risks with 2.0.18 will grow to be large. We've already made many changes and have deviated from 2.0.18 substantially (in good ways).

Let me dig into this more.

**Comment by jayninja** [comment] 2017-08-21 22:56
@brendandixon to cite the documentation I mentioned in my original post:
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/agent-user-guide

Provisioning.Enabled:
Type: Boolean
Default: y
This allows the user to enable or disable the provisioning functionality in the agent. Valid values are "y" or "n". **If provisioning is disabled, SSH host and user keys in the image are preserved and any configuration specified in the Azure provisioning API is ignored.**

**Comment by szarkos** [comment] 2017-08-21 22:58
There are a couple issues discussed here I think, so just to clarify the request - it sounds like you want to simply disable "provisioning" (i.e. setting up a user/pass/hostname/etc.), but still allow the VM to be marked as "ready" when creating a new VM from a generalized image (such as a Marketplace image).  Is that basically right?

It's correct that in the older 2.0 agent if "Provisioning.Enabled=no" then health reports would still be sent because the agent used the response to obtain the goalstate incarnation number (https://github.com/Azure/WALinuxAgent/blob/archive/2.0/waagent#L6262).  The successful health report would also cause the fabric to mark the VM as "ready" in those cases.  But if provisioning was enabled then no health reports would happen until "provisioning" succeeded.  I'm not certain what the current behavior is.

**Comment by jayninja** [comment] 2017-08-21 23:27
@szarkos thanks, that answers why it used to work. 

Unfortunately the change from 2.0 to 2.2 puts us in a bind. We will have to continue to ship the 2.0 agent like @jnoxon.  

I think it would be cool to see a more granular config file. So we can disable user creation, passwd, ssh_reconfigure, and the entire extension subsystem. Without losing the helpful stuff like HostnameMonitoring, and... well... provisioning.

**Comment by jnoxon** [comment] 2017-08-22 15:09
It sounds like @jayninja and I are after exactly the same thing: Disabling extensions and anything that would allow a user to gain access to the virtual machine.

**Comment by brendandixon** [comment] 2017-08-22 17:02
@jayninja @jnoxon @szarkos After reviewing both the latest code and the older 2.0.x branch, I believe we have a regression in the new code. We will re-align our next release (2.2.15) to behave as closely as is reasonable to the 2.0.x branch if `Provision.Enabled` is set to `n`. The agent will report "ready" and write the provisioned file, but it will do no other provisioning related work.

**Comment by szarkos** [comment] 2017-08-22 18:08
WALA may not always want to report "ready" if it is not responsible for provisioning.  I think one reason this change occurred in later WALA versions was to better support non-WALA provisioning agents, such as cloud-init.  In those cases the agent no longer has insight into whether provisioning has actually succeeded or not, and so it should be the responsibility of the other provisioning agent to signal "ready".

Maybe consider a more nuanced approach, i.e.:

  - If "Provisioning.Enabled=n" and "Provisioning.UseCloudInit=y," then don't report ready.  Assume cloud-init will handle the "ready" signal since it's handling this part.
  - If Provisioning.Enabled=n and Provisioning.UseCloudInit=n, then report ready.  Assume in this case there is no provisioning agent and thus we should just mark the VM as "ready".

Thoughts?

**Comment by brendandixon** [comment] 2017-08-22 18:13
@szarkos That is how it will behave. The default provisioning handler is engaged *only* when `Provision.UseCloudInit` is false. In that case, checking for `Provision.Enabled` and reporting ready when it's false is sound. When `Provision.UseCloudInit` is true, the default provisioning handler does not run nor is `Provision.Enabled` evaluated. In that case, reporting ready will depend solely on the success of `cloud-init`.

**Comment by brendandixon** [comment] 2017-08-22 21:00
Addressed by #851

**Closed by brendandixon** 2017-08-22 21:00 UTC
