### ISSUE TITLE
Support ephemeral disk handling on Gen2 VMs

### ISSUE THREAD

**Issue by szarkos** [Azure/WALinuxAgent#1362] opened 2018-10-11 22:44 UTC
Generation 2 VMs are becoming available in Azure, first for Azure Confidential Computing (ACC).  The current portal experience is exposed through https://aka.ms/ccvm. But folks can also use the CLI to deploy Standard_DC2s or Standard_DC4s VMs in East US or West Europe and provision Gen2 VMs in Azure.

The current ephemeral disk handling makes use of a "contract" relating to how the OS and ephemeral disks are attached to the VM.  With typical Gen1 VMs in Azure these disks are IDE disks, however Gen2 VMs only support SCSI disks.  See device_for_ide_port() and 66-azure-storage.rules for how detection works today.

On new Gen2 VMs, the OS disk will be added to <SCSI,0,0> and the resource disk will be added to <SCSI,0,1>.  The Azure agent and udev rule will need to be modified to properly detect the ephemeral disk for either Gen1 or Gen2 VMs.

**Comment by roiyz-msft** [comment] 2018-10-12 21:15
Taking a look

**Comment by szarkos** [comment] 2018-11-02 21:02
FYI, here is the associated cloud-init bug: https://bugs.launchpad.net/cloud-init/+bug/1797480

They have a merge proposal ready, which might help with this issue as well: https://code.launchpad.net/~chad.smith/cloud-init/+git/cloud-init/+merge/358190

**Comment by narrieta** [comment] 2018-12-08 00:40
@jasonzio - seems to be provisioning-related, could you take a peek? Thanks

**Comment by jasonzio** [comment] 2018-12-11 19:17
Fix was merged into upstream cloud-init on 2018-11-08. We have no control over how soon distro makers take the updated cloud-init and integrate it into the images we support in Azure. I would expect Ubuntu 19.04 to include this change, but I have no idea how soon the 18.04LTS image would be updated to include the change.

Consider building a custom image (using packer) which installs the latest cloud-init package from Ubuntu; I suspect that would get you the results you seek.

**Comment by szarkos** [comment] 2019-05-21 15:37
Ping on this - it seems we lost sight of this issue.  Mv2 series is GA, and Gen2 VMs are now public preview.  Unfortunately this bug means that the ephemeral disk remains NTFS formatted for Gen2 systems that use the Azure Agent to provision.

**Comment by jasonzio** [comment] 2019-06-13 01:17
Steve, the images for Ubuntu 18.04, 18.10, and 19.04 have all been updated to include cloud-init 19.1, which includes the fix for this issue; those distros all use cloud-init to handle provisioning (rather than waagent). Does this problem repro with the current published official Ubuntu images?

**Comment by szarkos** [comment] 2019-06-13 02:20
@jasonzio, we can follow up offline and loop in Simon from our test team for this info.  I don't think it's relevant for this bug report.

The target for this issue is every other distro that uses walinuxagent for provisioning.

**Comment by vrdmr** [comment] 2019-10-24 19:22
@trstringer Is this again a duplicate of #1654?

**Comment by trstringer** [comment] 2019-10-24 20:23
@vrdmr that's correct, this issue was fixed in #1654.

**Comment by vrdmr** [comment] 2019-10-24 20:49
Fixed by #1654. Closing the issue. Thanks, @trstringer for the fix.

**Closed by vrdmr** 2019-10-24 20:49 UTC
Labels: provisioning
