### ISSUE TITLE
No name resolution on new Ubuntu 18.10 vm

### ISSUE THREAD

**Issue by ChadNedzlek** [Azure/WALinuxAgent#1476] opened 2019-02-26 21:48 UTC
I can't reopen https://github.com/Azure/WALinuxAgent/issues/1151, but this is just that bug again, but on 18.10 instead of 18.04. The fix for this issue hard codes a 18.04 version check into the files, so it's broken for every Ubuntu image going forward.

**Comment by MattGal** [comment] 2019-03-06 18:39
@narrieta could I get some kind of rough estimate when this might get addressed?

**Comment by jasonzio** [comment] 2019-03-07 00:48
Looks like systemd is here to stay, so the fix is pretty obvious. Not sure why @ChadNedzlek couldn't have done the one-line PR themselves, but... whatever. Here it is.

**Comment by narrieta** [comment] 2019-03-21 15:18
fixed by #1483

**Closed by narrieta** 2019-03-21 15:18 UTC
Labels: triage

**Comment by MattGal** [comment] 2019-04-25 17:04
This problem is still reproducing in the following Azure gallery images:
SKU: 18.10, Version: 18.10.201903200                  
SKU: 18.10-DAILY, Version:  18.10.201904190

I don't seem to be able to reactivate this issue though, should I open a new one?
