### ISSUE TITLE
'waagent -deprovision' on Ubuntu 1804 breaks internet connnectivity

### ISSUE THREAD

**Issue by iamshital** [Azure/WALinuxAgent#1215] opened 2018-06-18 18:18 UTC
In latest Ubuntu 1804 azure image, when we tried to capture a customized image, and performed `waagent -deprovision`, we couldn't able to connect to internet due to lost `/etc/resolv.conf file.` 

The VMs created by this customized image gets provisioned successfully but they fail to connect to Internet.

**Comment by boumenot** [comment] 2018-06-18 22:59
This appears to be a dupe of #1151, and is fixed in master.

**Closed by boumenot** 2018-06-18 22:59 UTC
Labels: bug, duplicate
